# Импорт данных в pandas

In [2]:
#импорт библиотеки pandas
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
import glob

In [ ]:
path = '/content/drive/MyDrive/Кадровые метрики/Подразделения'

In [ ]:
#Считываем данные с файлов. Обязательно указываем разделитель ';'.
#Разделитель можно посмотреть, открыв файл в блокноте. По умолчанию разделитель запятая.
df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')
#Обратите внимание, что в зависимости от расширения вашего файла используется соответствующий метод pd.read_csv или pd.read_excel
#В файлах xlsx в качестве разделителя выступает запятая ',' , которая в методе используется как разделитель по умолчанию, поэтому в параметрах метода разделитель не указан

In [ ]:
#по умолчанию из exel-файлов считывается первый лист
#если нам нужен другой лист через запятую указываем название листа: sheet_name = 'Лист2'
df_e2 = pd.read_excel('/content/drive/MyDrive/Employees.xlsx', sheet_name = 'Лист2')
df_e2

   тест
0  тест

# Общее знакомство с данными

In [ ]:
#выводим данные с датафрейма
df_p

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
...,...,...,...,...,...,...,...
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

**DataFrame** — это объект в pandas и двумерная структура данных, представляющая собой таблицу с метками для строк и столбцов. Каждый столбец в DataFrame является объектом типа **Series**. Вместе они формируют двумерную таблицу с общим индексом. В DataFrame присутствуют две оси индексации: index для строк и columns для столбцов.

In [ ]:
# параметр .shape показывает кол-во строк и столбцов (кортежем)
df_p.shape
#df_p.shape[0] только кол-во строк
#df_p.shape[1] только кол-во столбцов

(77, 7)

In [ ]:
#len - это базовая функция python,которая считает длину объекта. В нашем случае кол-во строк в датафрейме
len(df_p)

77

In [ ]:

type(df_p)

pandas.core.frame.DataFrame

In [ ]:
#.dtypes - параметр датафрейма, который показывает тип данных столбцов в датафрейме
df_p.dtypes

ProductID                 int64
ProductName              object
Product_Description      object
UnitPrice               float64
CategoryID                int64
CategoryName             object
Category_Description     object
dtype: object

In [ ]:
#info()- метод, который тоже показывает тип данных столбцов в датафрейме, но также кол-во не пустых строк
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductID             77 non-null     int64
 1   ProductName           77 non-null     object
 2   Product_Description   77 non-null     object
 3   UnitPrice             77 non-null     float64
 4   CategoryID            77 non-null     int64
 5   CategoryName          77 non-null     object
 6   Category_Description  77 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.3+ KB

In [ ]:
#метод .head(10) выводит первые 10 строк. Eсли в скобки не передавать кол-во строк, то выведет верхние 5 строк
df_p.head()

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
5,6,Grandma's Boysenberry Spread,12 - 8 oz jars,25.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
6,7,Uncle Bob's Organic Dried Pears,12 - 1 lb pkgs.,30.00,7,Produce,Dried fruit and bean curd
7,8,Northwoods Cranberry Sauce,12 - 12 oz jars,40.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
8,9,Mishi Kobe Niku,18 - 500 g pkgs.,97.00,6,Meat/Poultry,Prepared meats
9,10,Ikura,12 - 200 ml jars,31.00,8,Seafood,Seaweed and fish
10,11,Queso Cabrales,1 kg pkg.,21.00,4,Dairy Products,Cheeses
11,12,Queso Manchego La Pastora,10 - 500 g pkgs.,38.00,4,Dairy Products,Cheeses
12,13,Konbu,2 kg box,6.00,8,Seafood,Seaweed and fish
13,14,Tofu,40 - 100 g pkgs.,23.25,7,Produce,Dried fruit and bean curd
14,15,Genen Shouyu,24 - 250 ml bottles,15.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
15,16,Pavlova,32 - 500 g boxes,17.45,3,Confections,Desserts. candies. and sweet breads
16,17,Alice Mutton,20 - 1 kg tins,39.00,6,Meat/Poultry,Prepared meats
17,18,Carnarvon Tigers,16 kg pkg.,62.50,8,Seafood,Seaweed and fish
18,19,Teatime Chocolate Biscuits,10 boxes x 12 pieces,9.20,3,Confections,Desserts. candies. and sweet breads
19,20,Sir Rodney's Marmalade,30 gift boxes,81.00,3,Confections,Desserts. candies. and sweet breads
20,21,Sir Rodney's Scones,24 pkgs. x 4 pieces,10.00,3,Confections,Desserts. candies. and sweet breads
21,22,Gustaf's Knackebrod,24 - 500 g pkgs.,21.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal
22,23,Tunnbrod,12 - 250 g pkgs.,9.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
24,25,NuNuCa Nub-Nougat-Creme,20 - 450 g glasses,14.00,3,Confections,Desserts. candies. and sweet breads
25,26,Gumbar Gummibarchen,100 - 250 g bags,31.23,3,Confections,Desserts. candies. and sweet breads
26,27,Schoggi Schokolade,100 - 100 g pieces,43.90,3,Confections,Desserts. candies. and sweet breads
27,28,Rossle Sauerkraut,25 - 825 g cans,45.60,7,Produce,Dried fruit and bean curd
28,29,Th?ringer Rostbratwurst,50 bags x 30 sausgs.,123.79,6,Meat/Poultry,Prepared meats
29,30,Nord-Ost Matjeshering,10 - 200 g glasses,25.89,8,Seafood,Seaweed and fish
30,31,Gorgonzola Telino,12 - 100 g pkgs,12.50,4,Dairy Products,Cheeses
31,32,Mascarpone Fabioli,24 - 200 g pkgs.,32.00,4,Dairy Products,Cheeses
32,33,Geitost,500 g,2.50,4,Dairy Products,Cheeses
33,34,Sasquatch Ale,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
34,35,Steeleye Stout,24 - 12 oz bottles,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
35,36,Inlagd Sill,24 - 250 g jars,19.00,8,Seafood,Seaweed and fish
36,37,Gravad lax,12 - 500 g pkgs.,26.00,8,Seafood,Seaweed and fish
37,38,C?te de Blaye,12 - 75 cl bottles,263.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
38,39,Chartreuse verte,750 cc per bottle,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
39,40,Boston Crab Meat,24 - 4 oz tins,18.40,8,Seafood,Seaweed and fish

In [ ]:
#.tail(15) метод выводит последние 15 строк. Eсли в скобки не передавать кол-во строк, то выведет нижние 5 строк
df_p.tail(15)

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
62,63,Vegie-spread,15 - 625 g jars,43.90,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
63,64,Wimmers gute Semmelknodel,20 bags x 4 pieces,33.25,5,Grains/Cereals,Breads. crackers. pasta. and cereal
64,65,Louisiana Fiery Hot Pepper Sauce,32 - 8 oz bottles,21.05,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
65,66,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
66,67,Laughing Lumberjack Lager,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
67,68,Scottish Longbreads,10 boxes x 8 pieces,12.50,3,Confections,Desserts. candies. and sweet breads
68,69,Gudbrandsdalsost,10 kg pkg.,36.00,4,Dairy Products,Cheeses
69,70,Outback Lager,24 - 355 ml bottles,15.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
70,71,Flotemysost,10 - 500 g pkgs.,21.50,4,Dairy Products,Cheeses
71,72,Mozzarella di Giovanni,24 - 200 g pkgs.,34.80,4,Dairy Products,Cheeses
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

# Работа с отдельными столбцами

In [ ]:
#выводим данные с датафрейма
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#первый способ выбрать один столбец
df_o['Freight']

0      32.38
1      11.61
2      65.83
3      41.34
4      51.30
       ...
825    24.95
826    18.44
827     6.19
828    38.28
829     8.53
Name: Freight, Length: 830, dtype: float64

In [ ]:
#один отдельно выбранный столбец - это серия.Серия - это объект pandas, как и датафрейм
type(df_o['Freight'])

pandas.core.series.Series

In [ ]:
#с помощью метода .reset_index() можно серию перевести серию в датафрейм
df_o['Freight'].reset_index()

     index  Freight
0        0    32.38
1        1    11.61
2        2    65.83
3        3    41.34
4        4    51.30
..     ...      ...
825    825    24.95
826    826    18.44
827    827     6.19
828    828    38.28
829    829     8.53

[830 rows x 2 columns]

In [ ]:
#второй способ выбрать один столбец датафрейма. Вызываем через точку название столбца как параметр
df_o.Freight

0      32.38
1      11.61
2      65.83
3      41.34
4      51.30
       ...
825    24.95
826    18.44
827     6.19
828    38.28
829     8.53
Name: Freight, Length: 830, dtype: float64

In [ ]:
#если выводим 2 и более столбца, то передаем в df_o[] список из названий столбцов. Получаются двойные квадратные скобки
df_o[['EmployeeID','OrderDate', 'OrderID']]

     EmployeeID  OrderDate  OrderID
0             5 1996-07-04    10248
1             6 1996-07-05    10249
2             4 1996-07-08    10250
3             3 1996-07-08    10251
4             4 1996-07-09    10252
..          ...        ...      ...
825           2 1998-05-05    11073
826           7 1998-05-06    11074
827           8 1998-05-06    11075
828           4 1998-05-06    11076
829           1 1998-05-06    11077

[830 rows x 3 columns]

In [ ]:
#c помощью параметра columns можно вывести названия столбцов в списке. Это удобно когда нужно скорировать большинство столбцов
df_o.columns

Index(['OrderID', 'CustomerID', 'EmployeeID', 'OrderDate', 'RequiredDate',
       'ShippedDate', 'Freight'],
      dtype='object')

In [ ]:
#выводим все столбцы за минусом двух
df_o.drop(columns=['Freight','ShippedDate'])

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000
...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000

In [ ]:
#метод drop понастоящему не удалил столбцы
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

# Создание новых столбцов на основе существующих

In [ ]:
#выводим 5 строк с датафрейма
df_od.head()

   OrderID  ProductID  UnitPrice  Quantity  Discount
0    10248         11       14.0        12       0.0
1    10248         42        9.8        10       0.0
2    10248         72       34.8         5       0.0
3    10249         14       18.6         9       0.0
4    10249         51       42.4        40       0.0

In [ ]:
#Записываем расчеты по формуле в столбец df_od['Discount_fact']. Этот столбец создается в момент выполнения кода
#формула расчитывает скидку фактическую, Discount - это скидка в процентах, точнее в долях
df_od['Discount_fact']= df_od['UnitPrice']*df_od['Quantity']*df_od['Discount']

In [ ]:
#расчитываем оборот очищенный от фактической скидки
df_od['Revenue']= df_od['UnitPrice']*df_od['Quantity']-df_od['Discount_fact']

In [ ]:
#выводим данные с датафрема. Появились 2 новых столбца
df_od.head()

   OrderID  ProductID  UnitPrice  Quantity  Discount  Discount_fact  Revenue
0    10248         11       14.0        12       0.0            0.0    168.0
1    10248         42        9.8        10       0.0            0.0     98.0
2    10248         72       34.8         5       0.0            0.0    174.0
3    10249         14       18.6         9       0.0            0.0    167.4
4    10249         51       42.4        40       0.0            0.0   1696.0

Здесь и далее я буду переодически занова записывать в наши переменные данные из файлов. Это делается для того, чтобы обнулить манипуляции, которые мы проделали с данными выше. Например, чтобы в df_od (датафрейм из файла Order_details) не было двух добавленных нами в последних строках кода столбцов. К слову, этого можно было бы избежать, создав копию датафрейма и проводя манипуляции уже с ней, например, создав df_od2 = df_od. Но на практике это редко бывает полезно.

In [ ]:
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')

In [ ]:
#как видим, данные вернулись к оригинальным значениям и количеству, которые были в файле
df_od

      OrderID  ProductID  UnitPrice  Quantity  Discount
0       10248         11      14.00        12      0.00
1       10248         42       9.80        10      0.00
2       10248         72      34.80         5      0.00
3       10249         14      18.60         9      0.00
4       10249         51      42.40        40      0.00
...       ...        ...        ...       ...       ...
2150    11077         64      33.25         2      0.03
2151    11077         66      17.00         1      0.00
2152    11077         73      15.00         2      0.01
2153    11077         75       7.75         4      0.00
2154    11077         77      13.00         2      0.00

[2155 rows x 5 columns]

# Типы данных

In [ ]:
#возможные типы данных:

#object - текст
#int64 - целые числа
#float64 - числа с плавающей точкой
#datetime64 - дата / время
#bool - содержит данные типа True / False

In [ ]:
#выводим данные с датафрейма
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#каждый столбец в пределах датафрейма имеет собственный тип данных
df_o.dtypes

OrderID           int64
CustomerID       object
EmployeeID        int64
OrderDate        object
RequiredDate     object
ShippedDate      object
Freight         float64
dtype: object

In [ ]:
#даты в датафрейме df_o изначально имеют тип данных object, но правильнее поменять их тип данных на datetime64
#для этого есть метод pd.to_datetime()
df_o['OrderDate'] = pd.to_datetime(df_o['OrderDate'])
df_o['RequiredDate'] = pd.to_datetime(df_o['RequiredDate'])
df_o['ShippedDate'] = pd.to_datetime(df_o['ShippedDate'])

In [ ]:
#убеждаемся, что у дат поменялся тип данных
df_o.dtypes

OrderID                  int64
CustomerID              object
EmployeeID               int64
OrderDate       datetime64[ns]
RequiredDate    datetime64[ns]
ShippedDate     datetime64[ns]
Freight                float64
dtype: object

In [ ]:
#менять тип данных можно также методом astype()
#пример перевода типа данных int64 в object
df_o['OrderID']= df_o['OrderID'].astype('object')
df_o.dtypes

OrderID                 object
CustomerID              object
EmployeeID               int64
OrderDate       datetime64[ns]
RequiredDate    datetime64[ns]
ShippedDate     datetime64[ns]
Freight                float64
dtype: object

In [ ]:
# Параметр parse_dates позволяет автоматически преобразовать указанные столбцы в datetime непосредственно при чтении файла.
# Укажите список названий столбцов, которые нужно преобразовать

In [ ]:
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';', parse_dates=['ShippedDate', 'OrderDate'])
df_o.dtypes

OrderID                  int64
CustomerID              object
EmployeeID               int64
OrderDate       datetime64[ns]
RequiredDate            object
ShippedDate     datetime64[ns]
Freight                float64
dtype: object

In [ ]:
#даты с типом данных datetime64 можно отнимать
df_o['delivery_time']= df_o['ShippedDate']- df_o['OrderDate']

In [ ]:
#появился новый столбец delivery_time, в котором записана разница в днях
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,delivery_time
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16,32.38,12 days
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10,11.61,5 days
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12,65.83,4 days
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15,41.34,7 days
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11,51.30,2 days

In [ ]:
#у столбца delivery_time тип данных timedelta64[ns]
df_o.dtypes

OrderID                    int64
CustomerID                object
EmployeeID                 int64
OrderDate         datetime64[ns]
RequiredDate              object
ShippedDate       datetime64[ns]
Freight                  float64
delivery_time    timedelta64[ns]
dtype: object

In [ ]:
#isna() возвращает True - если значение пустое, False - если значение заполнено
df_o['ShippedDate_flag']=df_o['ShippedDate'].isna()

In [ ]:
#появился новый столбец ShippedDate_flag
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,delivery_time,ShippedDate_flag
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16,32.38,12 days,False
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10,11.61,5 days,False
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12,65.83,4 days,False
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15,41.34,7 days,False
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11,51.30,2 days,False
...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02 00:00:00.000,NaT,24.95,NaT,True
826,11074,SIMOB,7,1998-05-06,1998-06-03 00:00:00.000,NaT,18.44,NaT,True
827,11075,RICSU,8,1998-05-06,1998-06-03 00:00:00.000,NaT,6.19,NaT,True
828,11076,BONAP,4,1998-05-06,1998-06-03 00:00:00.000,NaT,38.28,NaT,True
829,11077,RATTC,1,1998-05-06,1998-06-03 00:00:00.000,NaT,8.53,NaT,True

In [ ]:
#у столбца df_o['ShippedDate_flag'] тип данных bool
df_o.dtypes

OrderID                       int64
CustomerID                   object
EmployeeID                    int64
OrderDate            datetime64[ns]
RequiredDate                 object
ShippedDate          datetime64[ns]
Freight                     float64
delivery_time       timedelta64[ns]
ShippedDate_flag               bool
dtype: object