In [1]:
#импортируем нужнуе библиотеки и данные
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

Mounted at /content/drive

# Фильтрация строк по одному условию

In [2]:
#операторы сравнения

# > больше
# < меньше
# >= больше либо равно
# <= меньше либо равно
# == равно
# != неравно
# isnull()

In [3]:
#меняем тип данных у столбца Orderdate на datetime64
df_o['OrderDate'] = pd.to_datetime(df_o['OrderDate'])

In [4]:
#выводим первые 5 строк с датафрейма df_o
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30

In [5]:
#выбираем товары/строки, которые относятся к категории Condiments
df_p[df_p['CategoryName']=='Condiments']

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
5,6,Grandma's Boysenberry Spread,12 - 8 oz jars,25.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
7,8,Northwoods Cranberry Sauce,12 - 12 oz jars,40.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
14,15,Genen Shouyu,24 - 250 ml bottles,15.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
43,44,Gula Malacca,20 - 2 kg bags,19.45,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
60,61,Sirop d'erable,24 - 500 ml bottles,28.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
62,63,Vegie-spread,15 - 625 g jars,43.90,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
64,65,Louisiana Fiery Hot Pepper Sauce,32 - 8 oz bottles,21.05,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
65,66,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [6]:
#второй вариант
df_p[df_p.CategoryName=='Condiments']

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
5,6,Grandma's Boysenberry Spread,12 - 8 oz jars,25.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
7,8,Northwoods Cranberry Sauce,12 - 12 oz jars,40.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
14,15,Genen Shouyu,24 - 250 ml bottles,15.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
43,44,Gula Malacca,20 - 2 kg bags,19.45,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
60,61,Sirop d'erable,24 - 500 ml bottles,28.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
62,63,Vegie-spread,15 - 625 g jars,43.90,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
64,65,Louisiana Fiery Hot Pepper Sauce,32 - 8 oz bottles,21.05,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
65,66,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [7]:
#выбираем товары/строки, которые не относятся к категории Condiments, с помощью ~ (не)
df_p[~(df_p['CategoryName']=='Condiments')]

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
6,7,Uncle Bob's Organic Dried Pears,12 - 1 lb pkgs.,30.00,7,Produce,Dried fruit and bean curd
8,9,Mishi Kobe Niku,18 - 500 g pkgs.,97.00,6,Meat/Poultry,Prepared meats
9,10,Ikura,12 - 200 ml jars,31.00,8,Seafood,Seaweed and fish
...,...,...,...,...,...,...,...
71,72,Mozzarella di Giovanni,24 - 200 g pkgs.,34.80,4,Dairy Products,Cheeses
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales

In [8]:
#еще один способ вывести товары, которые не входят в категорию Condiments, с помощью оператора не равно !=

df_p[df_p['CategoryName']!='Condiments']

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
6,7,Uncle Bob's Organic Dried Pears,12 - 1 lb pkgs.,30.00,7,Produce,Dried fruit and bean curd
8,9,Mishi Kobe Niku,18 - 500 g pkgs.,97.00,6,Meat/Poultry,Prepared meats
9,10,Ikura,12 - 200 ml jars,31.00,8,Seafood,Seaweed and fish
...,...,...,...,...,...,...,...
71,72,Mozzarella di Giovanni,24 - 200 g pkgs.,34.80,4,Dairy Products,Cheeses
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales

In [9]:
#после фильтрации мы можем работать дальше с датафреймом и, например, вывести нужные столбцы
df_p[~(df_p['CategoryName']=='Condiments')][['CategoryID','UnitPrice']]

    CategoryID  UnitPrice
0            1      18.00
1            1      19.00
6            7      30.00
8            6      97.00
9            8      31.00
..         ...        ...
71           4      34.80
72           8      15.00
73           7      10.00
74           1       7.75
75           1      18.00

[65 rows x 2 columns]

In [10]:
#выбираем товары с ценой меньше или равно 10
df_p[df_p['UnitPrice']<=10]

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
12,13,Konbu,2 kg box,6.00,8,Seafood,Seaweed and fish
18,19,Teatime Chocolate Biscuits,10 boxes x 12 pieces,9.20,3,Confections,Desserts. candies. and sweet breads
20,21,Sir Rodney's Scones,24 pkgs. x 4 pieces,10.00,3,Confections,Desserts. candies. and sweet breads
22,23,Tunnbrod,12 - 250 g pkgs.,9.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
32,33,Geitost,500 g,2.50,4,Dairy Products,Cheeses
40,41,Jack's New England Clam Chowder,12 - 12 oz cans,9.65,8,Seafood,Seaweed and fish
44,45,Rogede sild,1k pkg.,9.50,8,Seafood,Seaweed and fish
46,47,Zaanse koeken,10 - 4 oz boxes,9.50,3,Confections,Desserts. candies. and sweet breads
51,52,Filo Mix,16 - 2 kg boxes,7.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal
53,54,Tourtiere,16 pies,7.45,6,Meat/Poultry,Prepared meats
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales

In [11]:
#выводим заказы, которые были оформлены ранее 1996-07-08 включительно
df_o[df_o['OrderDate']<='1996-07-08']

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34

In [12]:
#выводим заказы, у которых дата доставки не указана
df_o[df_o['ShippedDate'].isnull()]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
760,11008,ERNSH,7,1998-04-08,1998-05-06 00:00:00.000,NaN,79.46
771,11019,RANCH,6,1998-04-13,1998-05-11 00:00:00.000,NaN,3.17
791,11039,LINOD,1,1998-04-21,1998-05-19 00:00:00.000,NaN,65.00
792,11040,GREAL,4,1998-04-22,1998-05-20 00:00:00.000,NaN,18.84
797,11045,BOTTM,6,1998-04-23,1998-05-21 00:00:00.000,NaN,70.58
803,11051,LAMAI,7,1998-04-27,1998-05-25 00:00:00.000,NaN,2.79
806,11054,CACTU,8,1998-04-28,1998-05-26 00:00:00.000,NaN,0.33
810,11058,BLAUS,9,1998-04-29,1998-05-27 00:00:00.000,NaN,31.14
811,11059,RICAR,2,1998-04-29,1998-06-10 00:00:00.000,NaN,85.80
813,11061,GREAL,4,1998-04-30,1998-06-11 00:00:00.000,NaN,14.01
814,11062,REGGC,4,1998-04-30,1998-05-28 00:00:00.000,NaN,29.93
817,11065,LILAS,8,1998-05-01,1998-05-29 00:00:00.000,NaN,12.91
820,11068,QUEEN,8,1998-05-04,1998-06-01 00:00:00.000,NaN,81.75
822,11070,LEHMS,2,1998-05-05,1998-06-02 00:00:00.000,NaN,136.00
823,11071,LILAS,1,1998-05-05,1998-06-02 00:00:00.000,NaN,0.93
824,11072,ERNSH,4,1998-05-05,1998-06-02 00:00:00.000,NaN,258.64
825,11073,PERIC,2,1998-05-05,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06,1998-06-03 00:00:00.000,NaN,8.53

In [13]:
#выводим заказы, у которых указаза дата доставки
df_o[~(df_o['ShippedDate'].isnull())]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
815,11063,HUNGO,3,1998-04-30,1998-05-28 00:00:00.000,1998-05-06 00:00:00.000,81.73
816,11064,SAVEA,1,1998-05-01,1998-05-29 00:00:00.000,1998-05-04 00:00:00.000,30.09
818,11066,WHITC,7,1998-05-01,1998-05-29 00:00:00.000,1998-05-04 00:00:00.000,44.72
819,11067,DRACD,1,1998-05-04,1998-05-18 00:00:00.000,1998-05-06 00:00:00.000,7.98
821,11069,TORTU,1,1998-05-04,1998-06-01 00:00:00.000,1998-05-06 00:00:00.000,15.67

# Фильтрация строк between и isin

In [14]:
#выводим первые 5 строк с датафрейма df_o
#формат данных серии OrderDate уже был нами ранее заменен на datetime64
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30

In [15]:
#выводим заказы, чей вес входит в диапазон
#параметр inclusive: отвечает за включение границ. То есть, устанавливать ли каждую границу как закрытую или открытую.
#Может принимать значения: 'both', 'neither', 'left', 'right'.
#по умолчанию 'both', что означает обе границы включены
#При значении аргумента inclusive="neither" граничные значения исключаются
#значения 'left' или 'right' показывают, какая граница будет ВКЛЮЧЕНА в диапазон, если нужно оставить только одну
#inclusive='left' оставит в диапазоне левую границу, но иключит правую
df_o[df_o['Freight'].between(10,20,inclusive='neither')]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
8,10256,WELLI,3,1996-07-15,1996-08-12 00:00:00.000,1996-07-17 00:00:00.000,13.97
28,10276,TORTU,8,1996-08-08,1996-08-22 00:00:00.000,1996-08-14 00:00:00.000,13.84
34,10282,ROMEY,4,1996-08-15,1996-09-12 00:00:00.000,1996-08-21 00:00:00.000,12.69
39,10287,RICAR,8,1996-08-22,1996-09-19 00:00:00.000,1996-08-28 00:00:00.000,12.76
...,...,...,...,...,...,...,...
812,11060,FRANS,2,1998-04-30,1998-05-28 00:00:00.000,1998-05-04 00:00:00.000,10.98
813,11061,GREAL,4,1998-04-30,1998-06-11 00:00:00.000,NaN,14.01
817,11065,LILAS,8,1998-05-01,1998-05-29 00:00:00.000,NaN,12.91
821,11069,TORTU,1,1998-05-04,1998-06-01 00:00:00.000,1998-05-06 00:00:00.000,15.67
826,11074,SIMOB,7,1998-05-06,1998-06-03 00:00:00.000,NaN,18.44

In [16]:
#заказы, оформленные сотрудниками, чьи id не в списке
df_o[~(df_o['EmployeeID'].isin([2,4,6]))]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
5,10253,HANAR,3,1996-07-10,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
6,10254,CHOPS,5,1996-07-11,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
7,10255,RICSU,9,1996-07-12,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
...,...,...,...,...,...,...,...
821,11069,TORTU,1,1998-05-04,1998-06-01 00:00:00.000,1998-05-06 00:00:00.000,15.67
823,11071,LILAS,1,1998-05-05,1998-06-02 00:00:00.000,NaN,0.93
826,11074,SIMOB,7,1998-05-06,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06,1998-06-03 00:00:00.000,NaN,6.19
829,11077,RATTC,1,1998-05-06,1998-06-03 00:00:00.000,NaN,8.53

In [17]:
#заказы клиентов, чьи ID в списке
df_o[df_o['CustomerID'].isin(['CHOPS','TORTU','RICSU'])]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
6,10254,CHOPS,5,1996-07-11,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
7,10255,RICSU,9,1996-07-12,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
28,10276,TORTU,8,1996-08-08,1996-08-22 00:00:00.000,1996-08-14 00:00:00.000,13.84
45,10293,TORTU,1,1996-08-29,1996-09-26 00:00:00.000,1996-09-11 00:00:00.000,21.18
56,10304,TORTU,1,1996-09-12,1996-10-10 00:00:00.000,1996-09-17 00:00:00.000,63.79
71,10319,TORTU,7,1996-10-02,1996-10-30 00:00:00.000,1996-10-11 00:00:00.000,64.50
122,10370,CHOPS,6,1996-12-03,1996-12-31 00:00:00.000,1996-12-27 00:00:00.000,1.17
171,10419,RICSU,4,1997-01-20,1997-02-17 00:00:00.000,1997-01-30 00:00:00.000,137.35
270,10518,TORTU,4,1997-04-25,1997-05-09 00:00:00.000,1997-05-05 00:00:00.000,218.15
271,10519,CHOPS,6,1997-04-28,1997-05-26 00:00:00.000,1997-05-01 00:00:00.000,91.76
289,10537,RICSU,1,1997-05-14,1997-05-28 00:00:00.000,1997-05-19 00:00:00.000,78.85
328,10576,TORTU,3,1997-06-23,1997-07-07 00:00:00.000,1997-06-30 00:00:00.000,18.56
418,10666,RICSU,7,1997-09-12,1997-10-10 00:00:00.000,1997-09-22 00:00:00.000,232.42
428,10676,TORTU,2,1997-09-22,1997-10-20 00:00:00.000,1997-09-29 00:00:00.000,2.01
483,10731,CHOPS,7,1997-11-06,1997-12-04 00:00:00.000,1997-11-14 00:00:00.000,96.65
498,10746,CHOPS,1,1997-11-19,1997-12-17 00:00:00.000,1997-11-21 00:00:00.000,31.43
503,10751,RICSU,3,1997-11-24,1997-12-22 00:00:00.000,1997-12-03 00:00:00.000,130.79
510,10758,RICSU,3,1997-11-28,1997-12-26 00:00:00.000,1997-12-04 00:00:00.000,138.17
594,10842,TORTU,1,1998-01-20,1998-02-17 00:00:00.000,1998-01-29 00:00:00.000,54.42
667,10915,TORTU,2,1998-02-27,1998-03-27 00:00:00.000,1998-03-02 00:00:00.000,3.51
683,10931,RICSU,4,1998-03-06,1998-03-20 00:00:00.000,1998-03-19 00:00:00.000,13.60
703,10951,RICSU,9,1998-03-16,1998-04-27 00:00:00.000,1998-04-07 00:00:00.000,30.85
718,10966,CHOPS,4,1998-03-20,1998-04-17 00:00:00.000,1998-04-08 00:00:00.000,27.19
781,11029,CHOPS,4,1998-04-16,1998-05-14 00:00:00.000,1998-04-27 00:00:00.000,47.84
785,11033,RICSU,7,1998-04-17,1998-05-15 00:00:00.000,1998-04-23 00:00:00.000,84.74
793,11041,CHOPS,3,1998-04-22,1998-05-20 00:00:00.000,1998-04-28 00:00:00.000,48.22
821,11069,TORTU,1,1998-05-04,1998-06-01 00:00:00.000,1998-05-06 00:00:00.000,15.67
827,11075,RICSU,8,1998-05-06,1998-06-03 00:00:00.000,NaN,6.19

# Фильтрация строк с and и or

In [18]:
#выводим первые 5 строк с датафрейма df_p
df_p.head()

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [36]:
#выводим товары категории Beverages, которые стоят больше 20
df_p[(df_p['CategoryName']=='Beverages') & (df_p['UnitPrice']>20)]

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
37,38,C?te de Blaye,12 - 75 cl bottles,263.5,1,Beverages,Soft drinks. coffees. teas. beers. and ales
42,43,Ipoh Coffee,16 - 500 g tins,46.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales

In [20]:
#выводим данные с датафрейма df_o
#формат данных серии OrderDate уже был нами ранее заменен на datetime64
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30

In [21]:
#заказы, оформленные в период с 1996-07-08 по 1996-10-06 сотрудником с id = 4
df_o[(df_o['OrderDate'].between('1996-07-08','1996-10-06'))&(df_o['EmployeeID']==4)]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
9,10257,HILAA,4,1996-07-16,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,81.91
11,10259,CENTC,4,1996-07-18,1996-08-15 00:00:00.000,1996-07-25 00:00:00.000,3.25
12,10260,OTTIK,4,1996-07-19,1996-08-16 00:00:00.000,1996-07-29 00:00:00.000,55.09
13,10261,QUEDE,4,1996-07-19,1996-08-16 00:00:00.000,1996-07-30 00:00:00.000,3.05
19,10267,FRANK,4,1996-07-29,1996-08-26 00:00:00.000,1996-08-06 00:00:00.000,208.58
33,10281,ROMEY,4,1996-08-14,1996-08-28 00:00:00.000,1996-08-21 00:00:00.000,2.94
34,10282,ROMEY,4,1996-08-15,1996-09-12 00:00:00.000,1996-08-21 00:00:00.000,12.69
36,10284,LEHMS,4,1996-08-19,1996-09-16 00:00:00.000,1996-08-27 00:00:00.000,76.56
40,10288,REGGC,4,1996-08-23,1996-09-20 00:00:00.000,1996-09-03 00:00:00.000,7.45
46,10294,RATTC,4,1996-08-30,1996-09-27 00:00:00.000,1996-09-05 00:00:00.000,147.26
51,10299,RICAR,4,1996-09-06,1996-10-04 00:00:00.000,1996-09-13 00:00:00.000,29.76
54,10302,SUPRD,4,1996-09-10,1996-10-08 00:00:00.000,1996-10-09 00:00:00.000,6.27
67,10315,ISLAT,4,1996-09-26,1996-10-24 00:00:00.000,1996-10-03 00:00:00.000,41.76

In [22]:
#заказы, оформленные в период с 1996-07-08 по 1996-10-06, или заказы, оформленные сотрудником с id = 4
df_o[(df_o['OrderDate'].between('1996-07-08','1996-10-06'))|(df_o['EmployeeID']==4)]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
5,10253,HANAR,3,1996-07-10,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
6,10254,CHOPS,5,1996-07-11,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
...,...,...,...,...,...,...,...
796,11044,WOLZA,4,1998-04-23,1998-05-21 00:00:00.000,1998-05-01 00:00:00.000,8.72
813,11061,GREAL,4,1998-04-30,1998-06-11 00:00:00.000,NaN,14.01
814,11062,REGGC,4,1998-04-30,1998-05-28 00:00:00.000,NaN,29.93
824,11072,ERNSH,4,1998-05-05,1998-06-02 00:00:00.000,NaN,258.64
828,11076,BONAP,4,1998-05-06,1998-06-03 00:00:00.000,NaN,38.28

# Фильтрация по строковым данным

In [23]:
#выводим первые 30 строк датафрейма
df_c.head(30)

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
1,ANATR,Ana Trujillo,Owner,(5) 555-4729,Avda. de la Constitucion 2222
2,ANTON,Antonio Moreno,Owner,(5) 555-3932,Mataderos 2312
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
4,BERGS,Christina Berglund,Order Administrator,0921-12 34 65,Berguvsv?gen 8
5,BLAUS,Hanna Moos,Sales Representative,0621-08460,Forsterstr. 57
6,BLONP,Frederique Citeaux,Marketing Manager,88.60.15.31,"24, place Kleber"
7,BOLID,Martin Sommer,Owner,(91) 555 22 82,"C/ Araquil, 67"
8,BONAP,Laurence Lebihan,Owner,91.24.45.40,"12, rue des Bouchers"
9,BOTTM,Elizabeth Lincoln,Accounting Manager,(604) 555-4729,23 Tsawassen Blvd.
10,BSBEV,Victoria Ashworth,Sales Representative,(171) 555-1212,Fauntleroy Circus
11,CACTU,Patricio Simpson,Sales Agent,(1) 135-5555,Cerrito 333
12,CENTC,Francisco Chang,Marketing Manager,(5) 555-3392,Sierras de Granada 9993
13,CHOPS,Yang Wang,Owner,0452-076545,Hauptstr. 29
14,COMMI,Pedro Afonso,Sales Associate,(11) 555-7647,"Av. dos Lusiadas, 23"
15,CONSH,Elizabeth Brown,Sales Representative,(171) 555-2282,Berkeley Gardens 12 Brewery
16,DRACD,Sven Ottlieb,Order Administrator,0241-039123,Walserweg 21
17,DUMON,Janine Labrune,Owner,40.67.88.88,"67, rue des Cinquante Otages"
18,EASTC,Ann Devon,Sales Agent,(171) 555-0297,35 King George
19,ERNSH,Roland Mendel,Sales Manager,7675-3425,Kirchgasse 6
20,FAMIA,Aria Cruz,Marketing Assistant,(11) 555-9857,"Rua Oros, 92"
21,FISSA,Diego Roel,Accounting Manager,(91) 555 94 44,"C/ Moralzarzal, 86"
22,FOLIG,Martine Rance,Assistant Sales Agent,20.16.10.16,"184, chaussee de Tournai"
23,FOLKO,Maria Larsson,Owner,0695-34 67 21,Akergatan 24
24,FRANK,Peter Franken,Marketing Manager,089-0877310,Berliner Platz 43
25,FRANR,Carine Schmitt,Marketing Manager,40.32.21.21,"54, rue Royale"
26,FRANS,Paolo Accorti,Sales Representative,011-4988260,Via Monte Bianco 34
27,FURIB,Lino Rodriguez,Sales Manager,(1) 354-2534,Jardim das rosas n. 32
28,GALED,Eduardo Saavedra,Marketing Manager,(93) 203 4560,"Rambla de Catalu?a, 23"
29,GODOS,Jose Pedro Freyre,Sales Manager,(95) 555 82 82,"C/ Romero, 33"

In [24]:
#находим должности, в которых присуствует слово Sales. Неважно где.
df_c[df_c['ContactTitle'].str.contains('Sales')]

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
5,BLAUS,Hanna Moos,Sales Representative,0621-08460,Forsterstr. 57
10,BSBEV,Victoria Ashworth,Sales Representative,(171) 555-1212,Fauntleroy Circus
11,CACTU,Patricio Simpson,Sales Agent,(1) 135-5555,Cerrito 333
14,COMMI,Pedro Afonso,Sales Associate,(11) 555-7647,"Av. dos Lusiadas, 23"
15,CONSH,Elizabeth Brown,Sales Representative,(171) 555-2282,Berkeley Gardens 12 Brewery
18,EASTC,Ann Devon,Sales Agent,(171) 555-0297,35 King George
19,ERNSH,Roland Mendel,Sales Manager,7675-3425,Kirchgasse 6
22,FOLIG,Martine Rance,Assistant Sales Agent,20.16.10.16,"184, chaussee de Tournai"
26,FRANS,Paolo Accorti,Sales Representative,011-4988260,Via Monte Bianco 34
27,FURIB,Lino Rodriguez,Sales Manager,(1) 354-2534,Jardim das rosas n. 32
29,GODOS,Jose Pedro Freyre,Sales Manager,(95) 555 82 82,"C/ Romero, 33"
30,GOURL,Andre Fonseca,Sales Associate,(11) 555-9482,"Av. Brasil, 442"
34,HILAA,Carlos Hernandez,Sales Representative,(5) 555-1340,Carrera 22 con Ave. Carlos Soublette #8-35
35,HUNGC,Yoshi Latimer,Sales Representative,(503) 555-6874,City Center Plaza 516 Main St.
36,HUNGO,Patricia McKenna,Sales Associate,2 967 542,8 Johnstown Road
38,KOENE,Philip Cramer,Sales Associate,0555-09876,Maubelstr. 90
39,LACOR,Daniel Tonini,Sales Representative,30.59.84.10,"67, avenue de l'Europe"
40,LAMAI,Annette Roulet,Sales Manager,61.77.61.10,1 rue Alsace-Lorraine
43,LEHMS,Renate Messner,Sales Representative,069-0245984,Magazinweg 7
47,LONEP,Fran Wilson,Sales Manager,(503) 555-9573,89 Chiaroscuro Rd.
49,MAISD,Catherine Dewey,Sales Agent,(02) 201 24 67,Rue Joseph-Bens 532
52,NORTS,Simon Crowther,Sales Associate,(171) 555-7733,South House 300 Queensbridge
53,OCEAN,Yvonne Moncada,Sales Agent,(1) 135-5333,Ing. Gustavo Moncada 8585 Piso 20-A
54,OLDWO,Rene Phillips,Sales Representative,(907) 555-7584,2743 Bering St.
57,PERIC,Guillermo Fernandez,Sales Representative,(5) 552-3745,Calle Dr. Jorge Cash 321
58,PICCO,Georg Pipps,Sales Manager,6562-9722,Geislweg 14
59,PRINI,Isabel de Castro,Sales Representative,(1) 356-5634,Estrada da sa?de n. 58
63,RANCH,Sergio Gutierrez,Sales Representative,(1) 123-5555,Av. del Libertador 900
64,RATTC,Paula Wilson,Assistant Sales Representative,(505) 555-5939,2817 Milton Dr.
65,REGGC,Maurizio Moroni,Sales Associate,0522-556721,Strada Provinciale 124
66,RICAR,Janete Limeira,Assistant Sales Agent,(21) 555-3412,"Av. Copacabana, 267"
67,RICSU,Michael Holz,Sales Manager,0897-034214,Grenzacherweg 237
70,SAVEA,Jose Pavarotti,Sales Representative,(208) 555-8097,187 Suffolk Ln.
71,SEVES,Hari Kumar,Sales Manager,(171) 555-1717,90 Wadhurst Rd.
74,SPLIR,Art Braunschweiger,Sales Manager,(307) 555-4680,P.O. Box 555
80,TRADH,Anabela Domingues,Sales Representative,(11) 555-2167,"Av. Ines de Castro, 414"
81,TRAIH,Helvetius Nagy,Sales Associate,(206) 555-8257,722 DaVinci Blvd.
82,VAFFE,Palle Ibsen,Sales Manager,86 21 32 43,Smagsloget 45
83,VICTE,Mary Saveley,Sales Agent,78.32.54.86,"2, rue du Commerce"
85,WANDK,Rita Muller,Sales Representative,0711-020361,Adenauerallee 900
87,WELLI,Paula Parente,Sales Manager,(14) 555-8122,"Rua do Mercado, 12"

In [25]:
#Скорее всего Sales будет иметь разный регистр взависимости от положения в тексте (в реальной жизни).
#Поэтому предварительно можно перевести весть текст в нижний регистр.
df_c[df_c['ContactTitle'].str.lower().str.contains('sales')]

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
5,BLAUS,Hanna Moos,Sales Representative,0621-08460,Forsterstr. 57
10,BSBEV,Victoria Ashworth,Sales Representative,(171) 555-1212,Fauntleroy Circus
11,CACTU,Patricio Simpson,Sales Agent,(1) 135-5555,Cerrito 333
14,COMMI,Pedro Afonso,Sales Associate,(11) 555-7647,"Av. dos Lusiadas, 23"
15,CONSH,Elizabeth Brown,Sales Representative,(171) 555-2282,Berkeley Gardens 12 Brewery
18,EASTC,Ann Devon,Sales Agent,(171) 555-0297,35 King George
19,ERNSH,Roland Mendel,Sales Manager,7675-3425,Kirchgasse 6
22,FOLIG,Martine Rance,Assistant Sales Agent,20.16.10.16,"184, chaussee de Tournai"
26,FRANS,Paolo Accorti,Sales Representative,011-4988260,Via Monte Bianco 34
27,FURIB,Lino Rodriguez,Sales Manager,(1) 354-2534,Jardim das rosas n. 32
29,GODOS,Jose Pedro Freyre,Sales Manager,(95) 555 82 82,"C/ Romero, 33"
30,GOURL,Andre Fonseca,Sales Associate,(11) 555-9482,"Av. Brasil, 442"
34,HILAA,Carlos Hernandez,Sales Representative,(5) 555-1340,Carrera 22 con Ave. Carlos Soublette #8-35
35,HUNGC,Yoshi Latimer,Sales Representative,(503) 555-6874,City Center Plaza 516 Main St.
36,HUNGO,Patricia McKenna,Sales Associate,2 967 542,8 Johnstown Road
38,KOENE,Philip Cramer,Sales Associate,0555-09876,Maubelstr. 90
39,LACOR,Daniel Tonini,Sales Representative,30.59.84.10,"67, avenue de l'Europe"
40,LAMAI,Annette Roulet,Sales Manager,61.77.61.10,1 rue Alsace-Lorraine
43,LEHMS,Renate Messner,Sales Representative,069-0245984,Magazinweg 7
47,LONEP,Fran Wilson,Sales Manager,(503) 555-9573,89 Chiaroscuro Rd.
49,MAISD,Catherine Dewey,Sales Agent,(02) 201 24 67,Rue Joseph-Bens 532
52,NORTS,Simon Crowther,Sales Associate,(171) 555-7733,South House 300 Queensbridge
53,OCEAN,Yvonne Moncada,Sales Agent,(1) 135-5333,Ing. Gustavo Moncada 8585 Piso 20-A
54,OLDWO,Rene Phillips,Sales Representative,(907) 555-7584,2743 Bering St.
57,PERIC,Guillermo Fernandez,Sales Representative,(5) 552-3745,Calle Dr. Jorge Cash 321
58,PICCO,Georg Pipps,Sales Manager,6562-9722,Geislweg 14
59,PRINI,Isabel de Castro,Sales Representative,(1) 356-5634,Estrada da sa?de n. 58
63,RANCH,Sergio Gutierrez,Sales Representative,(1) 123-5555,Av. del Libertador 900
64,RATTC,Paula Wilson,Assistant Sales Representative,(505) 555-5939,2817 Milton Dr.
65,REGGC,Maurizio Moroni,Sales Associate,0522-556721,Strada Provinciale 124
66,RICAR,Janete Limeira,Assistant Sales Agent,(21) 555-3412,"Av. Copacabana, 267"
67,RICSU,Michael Holz,Sales Manager,0897-034214,Grenzacherweg 237
70,SAVEA,Jose Pavarotti,Sales Representative,(208) 555-8097,187 Suffolk Ln.
71,SEVES,Hari Kumar,Sales Manager,(171) 555-1717,90 Wadhurst Rd.
74,SPLIR,Art Braunschweiger,Sales Manager,(307) 555-4680,P.O. Box 555
80,TRADH,Anabela Domingues,Sales Representative,(11) 555-2167,"Av. Ines de Castro, 414"
81,TRAIH,Helvetius Nagy,Sales Associate,(206) 555-8257,722 DaVinci Blvd.
82,VAFFE,Palle Ibsen,Sales Manager,86 21 32 43,Smagsloget 45
83,VICTE,Mary Saveley,Sales Agent,78.32.54.86,"2, rue du Commerce"
85,WANDK,Rita Muller,Sales Representative,0711-020361,Adenauerallee 900
87,WELLI,Paula Parente,Sales Manager,(14) 555-8122,"Rua do Mercado, 12"

In [26]:
#ищем должности, чьи названия начинаются с Sales
df_c[df_c['ContactTitle'].str.startswith('Sales')]

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
5,BLAUS,Hanna Moos,Sales Representative,0621-08460,Forsterstr. 57
10,BSBEV,Victoria Ashworth,Sales Representative,(171) 555-1212,Fauntleroy Circus
11,CACTU,Patricio Simpson,Sales Agent,(1) 135-5555,Cerrito 333
14,COMMI,Pedro Afonso,Sales Associate,(11) 555-7647,"Av. dos Lusiadas, 23"
15,CONSH,Elizabeth Brown,Sales Representative,(171) 555-2282,Berkeley Gardens 12 Brewery
18,EASTC,Ann Devon,Sales Agent,(171) 555-0297,35 King George
19,ERNSH,Roland Mendel,Sales Manager,7675-3425,Kirchgasse 6
26,FRANS,Paolo Accorti,Sales Representative,011-4988260,Via Monte Bianco 34
27,FURIB,Lino Rodriguez,Sales Manager,(1) 354-2534,Jardim das rosas n. 32
29,GODOS,Jose Pedro Freyre,Sales Manager,(95) 555 82 82,"C/ Romero, 33"
30,GOURL,Andre Fonseca,Sales Associate,(11) 555-9482,"Av. Brasil, 442"
34,HILAA,Carlos Hernandez,Sales Representative,(5) 555-1340,Carrera 22 con Ave. Carlos Soublette #8-35
35,HUNGC,Yoshi Latimer,Sales Representative,(503) 555-6874,City Center Plaza 516 Main St.
36,HUNGO,Patricia McKenna,Sales Associate,2 967 542,8 Johnstown Road
38,KOENE,Philip Cramer,Sales Associate,0555-09876,Maubelstr. 90
39,LACOR,Daniel Tonini,Sales Representative,30.59.84.10,"67, avenue de l'Europe"
40,LAMAI,Annette Roulet,Sales Manager,61.77.61.10,1 rue Alsace-Lorraine
43,LEHMS,Renate Messner,Sales Representative,069-0245984,Magazinweg 7
47,LONEP,Fran Wilson,Sales Manager,(503) 555-9573,89 Chiaroscuro Rd.
49,MAISD,Catherine Dewey,Sales Agent,(02) 201 24 67,Rue Joseph-Bens 532
52,NORTS,Simon Crowther,Sales Associate,(171) 555-7733,South House 300 Queensbridge
53,OCEAN,Yvonne Moncada,Sales Agent,(1) 135-5333,Ing. Gustavo Moncada 8585 Piso 20-A
54,OLDWO,Rene Phillips,Sales Representative,(907) 555-7584,2743 Bering St.
57,PERIC,Guillermo Fernandez,Sales Representative,(5) 552-3745,Calle Dr. Jorge Cash 321
58,PICCO,Georg Pipps,Sales Manager,6562-9722,Geislweg 14
59,PRINI,Isabel de Castro,Sales Representative,(1) 356-5634,Estrada da sa?de n. 58
63,RANCH,Sergio Gutierrez,Sales Representative,(1) 123-5555,Av. del Libertador 900
65,REGGC,Maurizio Moroni,Sales Associate,0522-556721,Strada Provinciale 124
67,RICSU,Michael Holz,Sales Manager,0897-034214,Grenzacherweg 237
70,SAVEA,Jose Pavarotti,Sales Representative,(208) 555-8097,187 Suffolk Ln.
71,SEVES,Hari Kumar,Sales Manager,(171) 555-1717,90 Wadhurst Rd.
74,SPLIR,Art Braunschweiger,Sales Manager,(307) 555-4680,P.O. Box 555
80,TRADH,Anabela Domingues,Sales Representative,(11) 555-2167,"Av. Ines de Castro, 414"
81,TRAIH,Helvetius Nagy,Sales Associate,(206) 555-8257,722 DaVinci Blvd.
82,VAFFE,Palle Ibsen,Sales Manager,86 21 32 43,Smagsloget 45
83,VICTE,Mary Saveley,Sales Agent,78.32.54.86,"2, rue du Commerce"
85,WANDK,Rita Muller,Sales Representative,0711-020361,Adenauerallee 900
87,WELLI,Paula Parente,Sales Manager,(14) 555-8122,"Rua do Mercado, 12"

In [27]:
#ищем должности, чьи названия заканчиваются на Manager
df_c[df_c['ContactTitle'].str.endswith('Manager')]

,CustomerID,ContactName,ContactTitle,Phone,Address
6,BLONP,Frederique Citeaux,Marketing Manager,88.60.15.31,"24, place Kleber"
9,BOTTM,Elizabeth Lincoln,Accounting Manager,(604) 555-4729,23 Tsawassen Blvd.
12,CENTC,Francisco Chang,Marketing Manager,(5) 555-3392,Sierras de Granada 9993
19,ERNSH,Roland Mendel,Sales Manager,7675-3425,Kirchgasse 6
21,FISSA,Diego Roel,Accounting Manager,(91) 555 94 44,"C/ Moralzarzal, 86"
24,FRANK,Peter Franken,Marketing Manager,089-0877310,Berliner Platz 43
25,FRANR,Carine Schmitt,Marketing Manager,40.32.21.21,"54, rue Royale"
27,FURIB,Lino Rodriguez,Sales Manager,(1) 354-2534,Jardim das rosas n. 32
28,GALED,Eduardo Saavedra,Marketing Manager,(93) 203 4560,"Rambla de Catalu?a, 23"
29,GODOS,Jose Pedro Freyre,Sales Manager,(95) 555 82 82,"C/ Romero, 33"
31,GREAL,Howard Snyder,Marketing Manager,(503) 555-7555,2732 Baker Blvd.
33,HANAR,Mario Pontes,Accounting Manager,(21) 555-0091,"Rua do Pa?o, 67"
37,ISLAT,Helen Bennett,Marketing Manager,(198) 555-8888,Garden House Crowther Way
40,LAMAI,Annette Roulet,Sales Manager,61.77.61.10,1 rue Alsace-Lorraine
42,LAZYK,John Steel,Marketing Manager,(509) 555-7969,12 Orchestra Terrace
45,LILAS,Carlos Gonzalez,Accounting Manager,(9) 331-6954,Carrera 52 con Ave. Bolivar #65-98 Llano Largo
47,LONEP,Fran Wilson,Sales Manager,(503) 555-9573,89 Chiaroscuro Rd.
48,MAGAA,Giovanni Rovelli,Marketing Manager,035-640230,Via Ludovico il Moro 22
58,PICCO,Georg Pipps,Sales Manager,6562-9722,Geislweg 14
60,QUEDE,Bernardo Batista,Accounting Manager,(21) 555-4252,"Rua da Panificadora, 12"
62,QUICK,Horst Kloss,Accounting Manager,0372-035188,Taucherstra?e 10
67,RICSU,Michael Holz,Sales Manager,0897-034214,Grenzacherweg 237
68,ROMEY,Alejandra Camino,Accounting Manager,(91) 745 6200,"Gran Via, 1"
71,SEVES,Hari Kumar,Sales Manager,(171) 555-1717,90 Wadhurst Rd.
73,SPECD,Dominique Perrier,Marketing Manager,(1) 47.55.60.10,"25, rue Lauriston"
74,SPLIR,Art Braunschweiger,Sales Manager,(307) 555-4680,P.O. Box 555
75,SUPRD,Pascale Cartrain,Accounting Manager,(071) 23 67 22 20,"Boulevard Tirou, 255"
76,THEBI,Liz Nixon,Marketing Manager,(503) 555-3612,89 Jefferson Way Suite 2
78,TOMSP,Karin Josephs,Marketing Manager,0251-031259,Luisenstr. 48
82,VAFFE,Palle Ibsen,Sales Manager,86 21 32 43,Smagsloget 45
84,VINET,Paul Henriot,Accounting Manager,26.47.15.10,59 rue de l'Abbaye
86,WARTH,Pirkko Koskitalo,Accounting Manager,981-443655,Torikatu 38
87,WELLI,Paula Parente,Sales Manager,(14) 555-8122,"Rua do Mercado, 12"

# Сортировка строк

In [28]:
#выводим 10 строк с датафрейма
df_p.head(10)

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
5,6,Grandma's Boysenberry Spread,12 - 8 oz jars,25.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
6,7,Uncle Bob's Organic Dried Pears,12 - 1 lb pkgs.,30.00,7,Produce,Dried fruit and bean curd
7,8,Northwoods Cranberry Sauce,12 - 12 oz jars,40.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
8,9,Mishi Kobe Niku,18 - 500 g pkgs.,97.00,6,Meat/Poultry,Prepared meats
9,10,Ikura,12 - 200 ml jars,31.00,8,Seafood,Seaweed and fish

In [29]:
#сортировка по возрастанию по столбцу CategoryName
df_p.sort_values('CategoryName')

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
69,70,Outback Lager,24 - 355 ml bottles,15.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
66,67,Laughing Lumberjack Lager,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
42,43,Ipoh Coffee,16 - 500 g tins,46.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
...,...,...,...,...,...,...,...
39,40,Boston Crab Meat,24 - 4 oz tins,18.40,8,Seafood,Seaweed and fish
40,41,Jack's New England Clam Chowder,12 - 12 oz cans,9.65,8,Seafood,Seaweed and fish
45,46,Spegesild,4 - 450 g glasses,12.00,8,Seafood,Seaweed and fish
17,18,Carnarvon Tigers,16 kg pkg.,62.50,8,Seafood,Seaweed and fish
9,10,Ikura,12 - 200 ml jars,31.00,8,Seafood,Seaweed and fish

In [30]:
#сортировка по убыванию по столбцу CategoryName
df_p.sort_values('CategoryName', ascending = False)

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
44,45,Rogede sild,1k pkg.,9.50,8,Seafood,Seaweed and fish
17,18,Carnarvon Tigers,16 kg pkg.,62.50,8,Seafood,Seaweed and fish
40,41,Jack's New England Clam Chowder,12 - 12 oz cans,9.65,8,Seafood,Seaweed and fish
39,40,Boston Crab Meat,24 - 4 oz tins,18.40,8,Seafood,Seaweed and fish
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
...,...,...,...,...,...,...,...
37,38,C?te de Blaye,12 - 75 cl bottles,263.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
34,35,Steeleye Stout,24 - 12 oz bottles,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
33,34,Sasquatch Ale,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
38,39,Chartreuse verte,750 cc per bottle,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales

In [31]:
#сортировка по убыванию по столбцу UnitPrice
df_p.sort_values('UnitPrice', ascending= False)

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
37,38,C?te de Blaye,12 - 75 cl bottles,263.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
28,29,Th?ringer Rostbratwurst,50 bags x 30 sausgs.,123.79,6,Meat/Poultry,Prepared meats
8,9,Mishi Kobe Niku,18 - 500 g pkgs.,97.00,6,Meat/Poultry,Prepared meats
19,20,Sir Rodney's Marmalade,30 gift boxes,81.00,3,Confections,Desserts. candies. and sweet breads
17,18,Carnarvon Tigers,16 kg pkg.,62.50,8,Seafood,Seaweed and fish
...,...,...,...,...,...,...,...
53,54,Tourtiere,16 pies,7.45,6,Meat/Poultry,Prepared meats
51,52,Filo Mix,16 - 2 kg boxes,7.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal
12,13,Konbu,2 kg box,6.00,8,Seafood,Seaweed and fish
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
32,33,Geitost,500 g,2.50,4,Dairy Products,Cheeses

In [32]:
#сортировка по двум столбцам
df_p.sort_values(['CategoryName','UnitPrice'])
#сначала данные сортируются по первому столбцу в списке, а при одинаковых значениях - по второму и т.д.

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
33,34,Sasquatch Ale,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
66,67,Laughing Lumberjack Lager,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
69,70,Outback Lager,24 - 355 ml bottles,15.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
...,...,...,...,...,...,...,...
35,36,Inlagd Sill,24 - 250 g jars,19.00,8,Seafood,Seaweed and fish
29,30,Nord-Ost Matjeshering,10 - 200 g glasses,25.89,8,Seafood,Seaweed and fish
36,37,Gravad lax,12 - 500 g pkgs.,26.00,8,Seafood,Seaweed and fish
9,10,Ikura,12 - 200 ml jars,31.00,8,Seafood,Seaweed and fish
17,18,Carnarvon Tigers,16 kg pkg.,62.50,8,Seafood,Seaweed and fish

In [37]:
#Легко убедиться, что такая
df_p

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
...,...,...,...,...,...,...,...
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [34]:
#сортировка двух столбцов: цены по убыванию, названий категорий по возрастанию
df_p.sort_values(['CategoryName','UnitPrice'], ascending = [True, False]).head(30)
#количество элементов в списках должно совпадать

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
37,38,C?te de Blaye,12 - 75 cl bottles,263.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
42,43,Ipoh Coffee,16 - 500 g tins,46.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
34,35,Steeleye Stout,24 - 12 oz bottles,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
38,39,Chartreuse verte,750 cc per bottle,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
69,70,Outback Lager,24 - 355 ml bottles,15.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
33,34,Sasquatch Ale,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
66,67,Laughing Lumberjack Lager,24 - 12 oz bottles,14.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales
62,63,Vegie-spread,15 - 625 g jars,43.90,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
7,8,Northwoods Cranberry Sauce,12 - 12 oz jars,40.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
60,61,Sirop d'erable,24 - 500 ml bottles,28.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
5,6,Grandma's Boysenberry Spread,12 - 8 oz jars,25.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
64,65,Louisiana Fiery Hot Pepper Sauce,32 - 8 oz bottles,21.05,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
43,44,Gula Malacca,20 - 2 kg bags,19.45,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
65,66,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
14,15,Genen Shouyu,24 - 250 ml bottles,15.50,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
19,20,Sir Rodney's Marmalade,30 gift boxes,81.00,3,Confections,Desserts. candies. and sweet breads
61,62,Tarte au sucre,48 pies,49.30,3,Confections,Desserts. candies. and sweet breads
26,27,Schoggi Schokolade,100 - 100 g pieces,43.90,3,Confections,Desserts. candies. and sweet breads
25,26,Gumbar Gummibarchen,100 - 250 g bags,31.23,3,Confections,Desserts. candies. and sweet breads
48,49,Maxilaku,24 - 50 g pkgs.,20.00,3,Confections,Desserts. candies. and sweet breads
15,16,Pavlova,32 - 500 g boxes,17.45,3,Confections,Desserts. candies. and sweet breads