In [1]:
#импортируем нужнуе библиотеки и данные
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

Mounted at /content/drive

# Агрегирующие функции

In [2]:
#популярные агрегирующие функции

#count
#min
#max
#mean или median
#sum

In [3]:
#выводим первые 5 строк с датафрейма df_o
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30

In [4]:
#меняем тип данных даты заказа на datetime64
df_o['OrderDate'] = pd.to_datetime(df_o['OrderDate'])

In [5]:
#считаем количество не пустых строк
df_o.count()

OrderID         830
CustomerID      830
EmployeeID      830
OrderDate       830
RequiredDate    830
ShippedDate     809
Freight         830
dtype: int64

In [6]:
#считаем количество не пустых строк в столбце OrderDate
df_o['OrderDate'].count()

np.int64(830)

In [7]:
#количество уникальных строк в столбце OrderDate
df_o['OrderDate'].nunique()

480

In [8]:
#cписок уникальных значений столбца OrderDate
df_o['OrderDate'].unique()

<DatetimeArray>
['1996-07-04 00:00:00', '1996-07-05 00:00:00', '1996-07-08 00:00:00',
 '1996-07-09 00:00:00', '1996-07-10 00:00:00', '1996-07-11 00:00:00',
 '1996-07-12 00:00:00', '1996-07-15 00:00:00', '1996-07-16 00:00:00',
 '1996-07-17 00:00:00',
 ...
 '1998-04-23 00:00:00', '1998-04-24 00:00:00', '1998-04-27 00:00:00',
 '1998-04-28 00:00:00', '1998-04-29 00:00:00', '1998-04-30 00:00:00',
 '1998-05-01 00:00:00', '1998-05-04 00:00:00', '1998-05-05 00:00:00',
 '1998-05-06 00:00:00']
Length: 480, dtype: datetime64[ns]

In [9]:
#получаем уникальные EmployeeID' списком
df_o['EmployeeID'].unique()

array([5, 6, 4, 3, 9, 1, 8, 2, 7])

In [10]:
#находим максимальную дату заказа
df_o['OrderDate'].max()

Timestamp('1998-05-06 00:00:00')

In [11]:
#находим максимальный вес заказа
df_o['Freight'].max()

1007.64

In [12]:
#применение нескольких агрегирующих функций к столбцу с помощью метода .agg(). В метод передаем список агрегирующих функций.
#mean - среднее значение
df_o['Freight'].agg(['min','max','mean'])

min        0.020000
max     1007.640000
mean      78.244205
Name: Freight, dtype: float64

In [13]:
#применение агрегирующих функций к разным столбцам
#передаем в метод agg словарь, где первый ключ-значение - это столбец и список агрегирующих функций,
#второй ключ-значение - это столбец и агрегирующая функция
df_o.agg({'Freight':['min','max','mean'],'ShippedDate':'count'})

           Freight  ShippedDate
min       0.020000          NaN
max    1007.640000          NaN
mean     78.244205          NaN
count          NaN        809.0

# Агрегирующие функции после фильтрации

In [14]:
#выводим первые 5 строк с датафрейма df_p
df_p.head()

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [15]:
#cначала отбираем товары категории Beverages, а затем посчитали количество товаров
df_p[df_p['CategoryName']=='Beverages']['ProductID'].count()

np.int64(12)

In [16]:
#второй более удобный способ
df_p[df_p['CategoryName']=='Beverages'].ProductID.count()

np.int64(12)

In [17]:
#считаем минимальнаю стоймость товаров в категории Beverage
df_p[df_p['CategoryName']=='Beverages'].UnitPrice.min()

4.5

In [18]:
#минимальная и максимальная стоймость товаров в категории Beverage
df_p[df_p['CategoryName']=='Beverages'].UnitPrice.agg(['min','max'])

min      4.5
max    263.5
Name: UnitPrice, dtype: float64

In [19]:
#выводим данные с датафрейма df_o
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30

In [20]:
#суммарный вес заказов, совершенных в 1996 году
df_o[df_o['OrderDate'].between('1996-01-01','1996-12-31')].Freight.sum()

np.float64(10279.869999999999)

# Группиовка строк по одному столбцу

In [21]:
#выводим 5 первых строк с датафрейма df_p
df_p.head()

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [22]:
#считаем количество продуктов по каждой категории
# в groupby передаем название столбца по которому группируем
#получилась серия, где названия категорий - это индексы серии
df_p.groupby('CategoryName').ProductID.count()

CategoryName
Beverages         12
Condiments        12
Confections       13
Dairy Products    10
Grains/Cereals     7
Meat/Poultry       6
Produce            5
Seafood           12
Name: ProductID, dtype: int64

In [23]:
#переводим серию в датафрейм, а названия категорий из индексов в значения с помощью метода .reset_index()
df_p.groupby('CategoryName').ProductID.count().reset_index()

     CategoryName  ProductID
0       Beverages         12
1      Condiments         12
2     Confections         13
3  Dairy Products         10
4  Grains/Cereals          7
5    Meat/Poultry          6
6         Produce          5
7         Seafood         12

In [24]:
#минимальная стоймость товара в каждой категории
df_p.groupby('CategoryName').UnitPrice.min().reset_index()

     CategoryName  UnitPrice
0       Beverages       4.50
1      Condiments      10.00
2     Confections       9.20
3  Dairy Products       2.50
4  Grains/Cereals       7.00
5    Meat/Poultry       7.45
6         Produce      10.00
7         Seafood       6.00

In [25]:
#минимальная и максимальная стоймость товара в каждой категории
df_p.groupby('CategoryName').UnitPrice.agg(['min','max']).reset_index()

     CategoryName    min     max
0       Beverages   4.50  263.50
1      Condiments  10.00   43.90
2     Confections   9.20   81.00
3  Dairy Products   2.50   55.00
4  Grains/Cereals   7.00   38.00
5    Meat/Poultry   7.45  123.79
6         Produce  10.00   53.00
7         Seafood   6.00   62.50

In [26]:
#минимальная стоймость товара и количество товаров в каждой категории
df_p.groupby('CategoryName').agg({'UnitPrice':'min','ProductID':'count'}).reset_index()

     CategoryName  UnitPrice  ProductID
0       Beverages       4.50         12
1      Condiments      10.00         12
2     Confections       9.20         13
3  Dairy Products       2.50         10
4  Grains/Cereals       7.00          7
5    Meat/Poultry       7.45          6
6         Produce      10.00          5
7         Seafood       6.00         12

In [27]:
#выводим данные с датафрейма df_o
#у части заказов не указана дата доставки ShippedDate
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06,1998-06-03 00:00:00.000,NaN,8.53

In [28]:
#кол-во заказов в разрезе дней доставки
# дополнительный параметр dropna= False позволяет посчитать количество заказов, у которых дата доставки пустая
df_o.groupby('ShippedDate',dropna= False).OrderID.count().reset_index()

                 ShippedDate  OrderID
0    1996-07-10 00:00:00.000        1
1    1996-07-11 00:00:00.000        1
2    1996-07-12 00:00:00.000        1
3    1996-07-15 00:00:00.000        2
4    1996-07-16 00:00:00.000        2
..                       ...      ...
383  1998-05-01 00:00:00.000        6
384  1998-05-04 00:00:00.000        5
385  1998-05-05 00:00:00.000        2
386  1998-05-06 00:00:00.000        3
387                      NaN       21

[388 rows x 2 columns]

# Группировка по нескольким столбцам

In [29]:
#выводим данные с датафрейма df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06,1998-06-03 00:00:00.000,NaN,8.53

In [30]:
#если нужна группировка по 2 и более столбцам, передаем столбцы списком в метод .groupby()
#получили индексы состоящие из двух столбцов:EmployeeID и CustomerID
#такая комбинация индексов еще называется мультииндексом, но нам все равно избавимся от них с помощью метода .reset_index()
df_o.groupby(['EmployeeID','CustomerID']).OrderID.count()

EmployeeID  CustomerID
1           ALFKI         2
            ANTON         1
            AROUT         3
            BERGS         4
            BONAP         3
                         ..
9           SAVEA         1
            SUPRD         1
            TRAIH         1
            WARTH         1
            WELLI         1
Name: OrderID, Length: 464, dtype: int64

In [31]:
df_o.groupby(['EmployeeID','CustomerID']).OrderID.count().reset_index()

     EmployeeID CustomerID  OrderID
0             1      ALFKI        2
1             1      ANTON        1
2             1      AROUT        3
3             1      BERGS        4
4             1      BONAP        3
..          ...        ...      ...
459           9      SAVEA        1
460           9      SUPRD        1
461           9      TRAIH        1
462           9      WARTH        1
463           9      WELLI        1

[464 rows x 3 columns]

In [32]:
#выводим данные с датафрейма df_od
df_od

      OrderID  ProductID  UnitPrice  Quantity  Discount
0       10248         11      14.00        12      0.00
1       10248         42       9.80        10      0.00
2       10248         72      34.80         5      0.00
3       10249         14      18.60         9      0.00
4       10249         51      42.40        40      0.00
...       ...        ...        ...       ...       ...
2150    11077         64      33.25         2      0.03
2151    11077         66      17.00         1      0.00
2152    11077         73      15.00         2      0.01
2153    11077         75       7.75         4      0.00
2154    11077         77      13.00         2      0.00

[2155 rows x 5 columns]

In [33]:
#cчитаем фактическую скидку по каждой строке
df_od['Discount_fact'] = df_od['UnitPrice']*df_od['Quantity']*df_od['Discount']

In [34]:
#считаем выручку очищенную от скидки по каждой строке
df_od['Revenue'] = df_od['UnitPrice']*df_od['Quantity']-df_od['Discount_fact']

In [35]:
#появились 2 новых столбца
df_od

,OrderID,ProductID,UnitPrice,Quantity,Discount,Discount_fact,Revenue
0,10248,11,14.00,12,0.00,0.000,168.000
1,10248,42,9.80,10,0.00,0.000,98.000
2,10248,72,34.80,5,0.00,0.000,174.000
3,10249,14,18.60,9,0.00,0.000,167.400
4,10249,51,42.40,40,0.00,0.000,1696.000
...,...,...,...,...,...,...,...
2150,11077,64,33.25,2,0.03,1.995,64.505
2151,11077,66,17.00,1,0.00,0.000,17.000
2152,11077,73,15.00,2,0.01,0.300,29.700
2153,11077,75,7.75,4,0.00,0.000,31.000
2154,11077,77,13.00,2,0.00,0.000,26.000

In [36]:
#считаем фактическую скидку и чистую выручку каждому заказу. Записываем результат в новый датафрейм df_od_2
df_od_2 = df_od.groupby('OrderID').agg({'Discount_fact':'sum','Revenue':'sum'}).reset_index()

In [37]:
#теперь выручка и скидка в разрезе каждого заказа, а кол-во заказов такое же как в df_o
df_od_2

     OrderID  Discount_fact    Revenue
0      10248         0.0000   440.0000
1      10249         0.0000  1863.4000
2      10250       260.4000  1552.6000
3      10251        16.7400   654.0600
4      10252       132.1000  3597.9000
..       ...            ...        ...
825    11073         0.0000   300.0000
826    11074        12.2150   232.0850
827    11075        87.9000   498.1000
828    11076       264.2500   792.7500
829    11077       118.8795  1255.7205

[830 rows x 3 columns]

In [38]:
#переименовываем столбцы c помощью метода rename
#в методе rename в качестве параметра указываем, что собираемся переименовывать колонки (columns)
#и после символа '=' передаем словарь, в котором ключ - это старое название, значение - новое название
#пар ключ-значение может быть несколько
df_od_2 = df_od_2.rename(columns={'Discount_fact':'Discount','Revenue':'Clean_revenue'})

In [39]:
#проверяем переименованны ли столбцы
df_od_2

     OrderID  Discount  Clean_revenue
0      10248    0.0000       440.0000
1      10249    0.0000      1863.4000
2      10250  260.4000      1552.6000
3      10251   16.7400       654.0600
4      10252  132.1000      3597.9000
..       ...       ...            ...
825    11073    0.0000       300.0000
826    11074   12.2150       232.0850
827    11075   87.9000       498.1000
828    11076  264.2500       792.7500
829    11077  118.8795      1255.7205

[830 rows x 3 columns]