In [ ]:
#импортируем нужнуе библиотеки и данные
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

Mounted at /content/drive

# Объединение нескольких таблиц по общим признакам

In [ ]:
#выводим 5 строк с df_od
df_od.head()

   OrderID  ProductID  UnitPrice  Quantity  Discount
0    10248         11       14.0        12       0.0
1    10248         42        9.8        10       0.0
2    10248         72       34.8         5       0.0
3    10249         14       18.6         9       0.0
4    10249         51       42.4        40       0.0

In [ ]:
#расчитываем фактическую скидку и очищенную выручку по каждому заказу. Записываем в новый датафрейм
df_od['Discount_fact'] = df_od['UnitPrice']*df_od['Quantity']*df_od['Discount']
df_od['Revenue'] = df_od['UnitPrice']*df_od['Quantity'] - df_od['Discount_fact']
df_od_2 = df_od.groupby('OrderID').agg({'Discount_fact':'sum','Revenue':'sum'}).reset_index()

In [ ]:
#830 строк, как и в датафрейме df_o
df_od_2

     OrderID  Discount_fact    Revenue
0      10248         0.0000   440.0000
1      10249         0.0000  1863.4000
2      10250       260.4000  1552.6000
3      10251        16.7400   654.0600
4      10252       132.1000  3597.9000
..       ...            ...        ...
825    11073         0.0000   300.0000
826    11074        12.2150   232.0850
827    11075        87.9000   498.1000
828    11076       264.2500   792.7500
829    11077       118.8795  1255.7205

[830 rows x 3 columns]

In [ ]:
#выводим данные с df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#соединяем 2 датафрейма по ключу OrderID c помощью метода .merge()
#сохраняем в df_o
df_o = df_o.merge(df_od_2)

In [ ]:
#проверяем. Появилось 2 новых столбца: фактическая скидка и выручка
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Discount_fact,Revenue
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38,0.0000,440.0000
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61,0.0000,1863.4000
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83,260.4000,1552.6000
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34,16.7400,654.0600
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30,132.1000,3597.9000
...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95,0.0000,300.0000
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44,12.2150,232.0850
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19,87.9000,498.1000
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28,264.2500,792.7500
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53,118.8795,1255.7205

In [ ]:
#считаем выручку по каждому сотруднику
df_o.groupby('EmployeeID').Revenue.sum()

EmployeeID
1    192107.6045
2    166537.7550
3    202812.8430
4    232890.8460
5     68792.2825
6     73913.1295
7    124568.2350
8    126862.2775
9     77308.0665
Name: Revenue, dtype: float64

In [ ]:
#выводим данные с df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Discount_fact,Revenue
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38,0.0000,440.0000
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61,0.0000,1863.4000
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83,260.4000,1552.6000
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34,16.7400,654.0600
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30,132.1000,3597.9000
...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95,0.0000,300.0000
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44,12.2150,232.0850
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19,87.9000,498.1000
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28,264.2500,792.7500
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53,118.8795,1255.7205

In [ ]:
#считаем кол-во клиентов, совершивших заказ
df_o['CustomerID'].nunique()

89

In [ ]:
#в таблице customers клиентов больше - 91. 2 клинта не совершали заказы
df_c

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
1,ANATR,Ana Trujillo,Owner,(5) 555-4729,Avda. de la Constitucion 2222
2,ANTON,Antonio Moreno,Owner,(5) 555-3932,Mataderos 2312
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
4,BERGS,Christina Berglund,Order Administrator,0921-12 34 65,Berguvsv?gen 8
...,...,...,...,...,...
86,WARTH,Pirkko Koskitalo,Accounting Manager,981-443655,Torikatu 38
87,WELLI,Paula Parente,Sales Manager,(14) 555-8122,"Rua do Mercado, 12"
88,WHITC,Karl Jablonski,Owner,(206) 555-4112,305 - 14th Ave. S. Suite 3B
89,WILMK,Matti Karttunen,Owner/Marketing Assistant,90-224 8858,Keskuskatu 45
90,WOLZA,Zbyszek Piestrzeniewicz,Owner,(26) 642-7012,ul. Filtrowa 68

In [ ]:
#оставляем в датафрейме df_c только 2 столбца
df_c = df_c[['CustomerID','ContactName']]

In [ ]:
#соединяем два датафрейма df_c и df_o
#указываем параметр how = 'left', чтобы вывести также клиентов, у которых нет заказов
#по аналогии с LEFT JOIN в SQL
df_o= df_c.merge(df_o, how = 'left')

In [ ]:
#проверяем результат соединения
df_o

,CustomerID,ContactName,OrderID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Discount_fact,Revenue
0,ALFKI,Maria Anders,10643.0,6.0,1997-08-25 00:00:00.000,1997-09-22 00:00:00.000,1997-09-02 00:00:00.000,29.46,271.5,814.50
1,ALFKI,Maria Anders,10692.0,4.0,1997-10-03 00:00:00.000,1997-10-31 00:00:00.000,1997-10-13 00:00:00.000,61.02,0.0,878.00
2,ALFKI,Maria Anders,10702.0,4.0,1997-10-13 00:00:00.000,1997-11-24 00:00:00.000,1997-10-21 00:00:00.000,23.94,0.0,330.00
3,ALFKI,Maria Anders,10835.0,1.0,1998-01-15 00:00:00.000,1998-02-12 00:00:00.000,1998-01-21 00:00:00.000,69.53,5.2,845.80
4,ALFKI,Maria Anders,10952.0,1.0,1998-03-16 00:00:00.000,1998-04-27 00:00:00.000,1998-03-24 00:00:00.000,40.42,20.0,471.20
...,...,...,...,...,...,...,...,...,...,...
827,WOLZA,Zbyszek Piestrzeniewicz,10792.0,1.0,1997-12-23 00:00:00.000,1998-01-20 00:00:00.000,1997-12-31 00:00:00.000,23.79,0.0,399.85
828,WOLZA,Zbyszek Piestrzeniewicz,10870.0,5.0,1998-02-04 00:00:00.000,1998-03-04 00:00:00.000,1998-02-13 00:00:00.000,12.04,0.0,160.00
829,WOLZA,Zbyszek Piestrzeniewicz,10906.0,4.0,1998-02-25 00:00:00.000,1998-03-11 00:00:00.000,1998-03-03 00:00:00.000,26.29,0.0,427.50
830,WOLZA,Zbyszek Piestrzeniewicz,10998.0,8.0,1998-04-03 00:00:00.000,1998-04-17 00:00:00.000,1998-04-17 00:00:00.000,20.31,0.0,686.00
831,WOLZA,Zbyszek Piestrzeniewicz,11044.0,4.0,1998-04-23 00:00:00.000,1998-05-21 00:00:00.000,1998-05-01 00:00:00.000,8.72,0.0,591.60

In [ ]:
#клиенты, у которых нет заказов
df_o[df_o['OrderID'].isnull()]

,CustomerID,ContactName,OrderID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Discount_fact,Revenue
188,FISSA,Diego Roel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,PARIS,Marie Bertrand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#считаем кол-во заказов в разрезе каждого клиента
df_o_result = df_o.groupby('ContactName').OrderID.count().reset_index()

In [ ]:
#два клиента, у которых 0 заказов
df_o_result.sort_values('OrderID')

         ContactName  OrderID
17        Diego Roel        0
56    Marie Bertrand        0
24   Francisco Chang        1
41        John Steel        2
53    Manuel Pereira        2
..               ...      ...
55     Maria Larsson       19
68  Patricia McKenna       19
34       Horst Kloss       28
80     Roland Mendel       30
43    Jose Pavarotti       31

[91 rows x 2 columns]

Чуть-чуть подробнее про merge() и варианты её использования

Функция merge() в Pandas используется для объединения двух или более DataFrame на основе общих столбцов или индексов. Это аналогично операции соединения в базах данных.

Параметр функции how — это тип слияния. Возможные значения: 'left', 'right', 'outer', 'inner', 'cross'.

По умолчанию используется 'inner', которое **объединяет только общие строки** между двумя DataFrame.

'left' — использует все столбцы из левого DataFrame независимо от того есть ли соотношение по общему ключу в правой таблице.

'right' — использует все столбцы из правого DataFrame независимо от того есть ли соотношение по общему ключу в левой таблице.

'outer' — использует объединение всех столбцов из обоих DataFrame.

'inner' — вернёт из левой и правой таблиц только те строки, по которым нашлись соответствия.

'cross' — создает декартово произведение обоих DataFrame (все строки одного датафрейма пересекаются со всеми строками второго датафрейма)

In [ ]:
#переименуем название столбца в датафрейме df_c
df_c= df_c.rename(columns = {'CustomerID':'CustID'})

In [ ]:
df_c.head()

  CustID         ContactName
0  ALFKI        Maria Anders
1  ANATR        Ana Trujillo
2  ANTON      Antonio Moreno
3  AROUT        Thomas Hardy
4  BERGS  Christina Berglund

In [ ]:
df_o.head()

,CustomerID,ContactName,OrderID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Discount_fact,Revenue
0,ALFKI,Maria Anders,10643.0,6.0,1997-08-25 00:00:00.000,1997-09-22 00:00:00.000,1997-09-02 00:00:00.000,29.46,271.5,814.5
1,ALFKI,Maria Anders,10692.0,4.0,1997-10-03 00:00:00.000,1997-10-31 00:00:00.000,1997-10-13 00:00:00.000,61.02,0.0,878.0
2,ALFKI,Maria Anders,10702.0,4.0,1997-10-13 00:00:00.000,1997-11-24 00:00:00.000,1997-10-21 00:00:00.000,23.94,0.0,330.0
3,ALFKI,Maria Anders,10835.0,1.0,1998-01-15 00:00:00.000,1998-02-12 00:00:00.000,1998-01-21 00:00:00.000,69.53,5.2,845.8
4,ALFKI,Maria Anders,10952.0,1.0,1998-03-16 00:00:00.000,1998-04-27 00:00:00.000,1998-03-24 00:00:00.000,40.42,20.0,471.2

Часто бывает, что ключи в таблицах называется по-разному. Например в датафрейме df_c ID клиента - это CustID, а в датафрейме df_o ID клиента - это CustomerID. В таком случае в методе .merge() нужно прописать дополнительные параметры left_on и right_on, где:

left_on - ключ левой таблицы (к которой присоединяем)

right_on - ключ правой таблицы (которую присоединяем)

In [ ]:
df_c.merge(df_o, left_on ='CustID', right_on = 'CustomerID')

,CustID,ContactName_x,CustomerID,ContactName_y,OrderID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Discount_fact,Revenue
0,ALFKI,Maria Anders,ALFKI,Maria Anders,10643.0,6.0,1997-08-25 00:00:00.000,1997-09-22 00:00:00.000,1997-09-02 00:00:00.000,29.46,271.5,814.50
1,ALFKI,Maria Anders,ALFKI,Maria Anders,10692.0,4.0,1997-10-03 00:00:00.000,1997-10-31 00:00:00.000,1997-10-13 00:00:00.000,61.02,0.0,878.00
2,ALFKI,Maria Anders,ALFKI,Maria Anders,10702.0,4.0,1997-10-13 00:00:00.000,1997-11-24 00:00:00.000,1997-10-21 00:00:00.000,23.94,0.0,330.00
3,ALFKI,Maria Anders,ALFKI,Maria Anders,10835.0,1.0,1998-01-15 00:00:00.000,1998-02-12 00:00:00.000,1998-01-21 00:00:00.000,69.53,5.2,845.80
4,ALFKI,Maria Anders,ALFKI,Maria Anders,10952.0,1.0,1998-03-16 00:00:00.000,1998-04-27 00:00:00.000,1998-03-24 00:00:00.000,40.42,20.0,471.20
...,...,...,...,...,...,...,...,...,...,...,...,...
827,WOLZA,Zbyszek Piestrzeniewicz,WOLZA,Zbyszek Piestrzeniewicz,10792.0,1.0,1997-12-23 00:00:00.000,1998-01-20 00:00:00.000,1997-12-31 00:00:00.000,23.79,0.0,399.85
828,WOLZA,Zbyszek Piestrzeniewicz,WOLZA,Zbyszek Piestrzeniewicz,10870.0,5.0,1998-02-04 00:00:00.000,1998-03-04 00:00:00.000,1998-02-13 00:00:00.000,12.04,0.0,160.00
829,WOLZA,Zbyszek Piestrzeniewicz,WOLZA,Zbyszek Piestrzeniewicz,10906.0,4.0,1998-02-25 00:00:00.000,1998-03-11 00:00:00.000,1998-03-03 00:00:00.000,26.29,0.0,427.50
830,WOLZA,Zbyszek Piestrzeniewicz,WOLZA,Zbyszek Piestrzeniewicz,10998.0,8.0,1998-04-03 00:00:00.000,1998-04-17 00:00:00.000,1998-04-17 00:00:00.000,20.31,0.0,686.00
831,WOLZA,Zbyszek Piestrzeniewicz,WOLZA,Zbyszek Piestrzeniewicz,11044.0,4.0,1998-04-23 00:00:00.000,1998-05-21 00:00:00.000,1998-05-01 00:00:00.000,8.72,0.0,591.60

Еще один **важнейший** нюанс:

В таблицах Products и Order_details есть общий ключ ProductID. Но также в этих таблицах есть еще один столбец с одинаковым именем UnitPrice. Причем UnitPrice в df_od - это стоимость продукта в момент оформления заказа, а UnitPrice в df_p - это стоимость продукта на «сегодняшний день». Стоимости продуктов в df_od и в df_p могут различаться.

Так как у нас 2 столбца, которые есть и в той и в другой таблице, этого кода будет недостаточно:

df_od.merge(df_p)

Потому что .merge()будет искать соответствия и по ProductID и по UnitPrice, что в свою очередь приведет к потере данных. Поэтому в методе .merge() необходимо явно прописать ключи.

In [ ]:
df_od.merge(df_p, left_on = 'ProductID', right_on = 'ProductID')

,OrderID,ProductID,UnitPrice_x,Quantity,Discount,Discount_fact,Revenue,ProductName,Product_Description,UnitPrice_y,CategoryID,CategoryName,Category_Description
0,10248,11,14.00,12,0.00,0.000,168.000,Queso Cabrales,1 kg pkg.,21.00,4,Dairy Products,Cheeses
1,10248,42,9.80,10,0.00,0.000,98.000,Singaporean Hokkien Fried Mee,32 - 1 kg pkgs.,14.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal
2,10248,72,34.80,5,0.00,0.000,174.000,Mozzarella di Giovanni,24 - 200 g pkgs.,34.80,4,Dairy Products,Cheeses
3,10249,14,18.60,9,0.00,0.000,167.400,Tofu,40 - 100 g pkgs.,23.25,7,Produce,Dried fruit and bean curd
4,10249,51,42.40,40,0.00,0.000,1696.000,Manjimup Dried Apples,50 - 300 g pkgs.,53.00,7,Produce,Dried fruit and bean curd
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150,11077,64,33.25,2,0.03,1.995,64.505,Wimmers gute Semmelknodel,20 bags x 4 pieces,33.25,5,Grains/Cereals,Breads. crackers. pasta. and cereal
2151,11077,66,17.00,1,0.00,0.000,17.000,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
2152,11077,73,15.00,2,0.01,0.300,29.700,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish
2153,11077,75,7.75,4,0.00,0.000,31.000,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2154,11077,77,13.00,2,0.00,0.000,26.000,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

Теперь названия столбцов UnitPrice поменялись на UnitPrice_x и UnitPrice_y.

In [34]:
# Переименовываем столбцы перед объединением
df_p_renamed = df_p.rename(columns={'UnitPrice': 'CurrentUnitPrice'})
df_od_renamed = df_od.rename(columns={'UnitPrice': 'OrderUnitPrice'})

# Объединяем по ProductID
merged_df = pd.merge(df_p_renamed, df_od_renamed, on='ProductID', how='inner')  # или другой тип соединения
merged_df

,ProductID,ProductName,Product_Description,CurrentUnitPrice,CategoryID,CategoryName,Category_Description,OrderID,OrderUnitPrice,Quantity,Discount
0,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10285,14.4,45,0.20
1,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10294,14.4,18,0.00
2,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10317,14.4,20,0.00
3,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10348,14.4,15,0.15
4,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10354,14.4,12,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2150,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11000,13.0,30,0.00
2151,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11015,13.0,18,0.00
2152,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11060,13.0,10,0.00
2153,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11068,13.0,28,0.15
2154,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11077,13.0,2,0.00

In [35]:
# Переименовываем в процессе объединения
merged_df = pd.merge(
    df_p.rename(columns={'UnitPrice': 'CurrentPrice'}),
    df_od.rename(columns={'UnitPrice': 'OrderPrice'}),
    on='ProductID'
)
merged_df

,ProductID,ProductName,Product_Description,CurrentPrice,CategoryID,CategoryName,Category_Description,OrderID,OrderPrice,Quantity,Discount
0,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10285,14.4,45,0.20
1,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10294,14.4,18,0.00
2,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10317,14.4,20,0.00
3,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10348,14.4,15,0.15
4,1,Chai,10 boxes x 20 bags,18.0,1,Beverages,Soft drinks. coffees. teas. beers. and ales,10354,14.4,12,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2150,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11000,13.0,30,0.00
2151,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11015,13.0,18,0.00
2152,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11060,13.0,10,0.00
2153,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11068,13.0,28,0.15
2154,77,Original Frankfurter gr?ne Sobe,12 boxes,13.0,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,11077,13.0,2,0.00

# Конкатенация

In [36]:
#обнулим внесенные в датафреймы изменения
df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

In [ ]:
#выводим 5 строк с таблицы df_e
df_e.head()

,EmployeeID,FirstName,LastName,Title,TitleOfCourtesy,BirthDate,HireDate,Address,HomePhone
0,1,Nancy,Davolio,Sales Representative,Ms.,1948-12-08 00:00:00.000,1992-05-01 00:00:00.000,507 - 20th Ave. E. Apt. 2A,(206) 555-9857
1,2,Andrew,Fuller,"Vice President, Sales",Dr.,1952-02-19 00:00:00.000,1992-08-14 00:00:00.000,908 W. Capital Way,(206) 555-9482
2,3,Janet,Leverling,Sales Representative,Ms.,1963-08-30 00:00:00.000,1992-04-01 00:00:00.000,722 Moss Bay Blvd.,(206) 555-3412
3,4,Margaret,Peacock,Sales Representative,Mrs.,1937-09-19 00:00:00.000,1993-05-03 00:00:00.000,4110 Old Redmond Rd.,(206) 555-8122
4,5,Steven,Buchanan,Sales Manager,Mr.,1955-03-04 00:00:00.000,1993-10-17 00:00:00.000,14 Garrett Hill,(71) 555-4848

In [ ]:
#выводим 5 строк с таблицы df_c
df_c.head()

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
1,ANATR,Ana Trujillo,Owner,(5) 555-4729,Avda. de la Constitucion 2222
2,ANTON,Antonio Moreno,Owner,(5) 555-3932,Mataderos 2312
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
4,BERGS,Christina Berglund,Order Administrator,0921-12 34 65,Berguvsv?gen 8

In [ ]:
#выводим должности сотрудников
df_e['Title']

0        Sales Representative
1       Vice President, Sales
2        Sales Representative
3        Sales Representative
4               Sales Manager
5        Sales Representative
6        Sales Representative
7    Inside Sales Coordinator
8        Sales Representative
Name: Title, dtype: object

In [ ]:
#делаем датафрейм из серии
a =pd.DataFrame({'Title':df_e['Title']})

In [ ]:
#выводим должности клиентов
df_c['ContactTitle']

0          Sales Representative
1                         Owner
2                         Owner
3          Sales Representative
4           Order Administrator
                ...
86           Accounting Manager
87                Sales Manager
88                        Owner
89    Owner/Marketing Assistant
90                        Owner
Name: ContactTitle, Length: 91, dtype: object

In [ ]:
#делаем датафрейм из серии
b = pd.DataFrame({'Title':df_c['ContactTitle']})

In [ ]:
#конкатенируем 2 датафрейма с помощью метода .concat()
pd.concat([a,b])

                        Title
0        Sales Representative
1       Vice President, Sales
2        Sales Representative
3        Sales Representative
4               Sales Manager
..                        ...
86         Accounting Manager
87              Sales Manager
88                      Owner
89  Owner/Marketing Assistant
90                      Owner

[100 rows x 1 columns]

In [ ]:
#конкатенируем 2 серии
pd.concat([df_e['Title'],df_c['ContactTitle']])

0          Sales Representative
1         Vice President, Sales
2          Sales Representative
3          Sales Representative
4                 Sales Manager
                ...
86           Accounting Manager
87                Sales Manager
88                        Owner
89    Owner/Marketing Assistant
90                        Owner
Length: 100, dtype: object

In [ ]:
#конкатенируем 2 серии и делаем из серии датафрейм
pd.DataFrame({'Title':pd.concat([df_e['Title'],df_c['ContactTitle']])})

                        Title
0        Sales Representative
1       Vice President, Sales
2        Sales Representative
3        Sales Representative
4               Sales Manager
..                        ...
86         Accounting Manager
87              Sales Manager
88                      Owner
89  Owner/Marketing Assistant
90                      Owner

[100 rows x 1 columns]