In [1]:
#импортируем нужнуе библиотеки и данные
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

Mounted at /content/drive

# Работа с датами

In [2]:
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [3]:
#сейчас даты имеют тип данных object
df_o.dtypes

OrderID           int64
CustomerID       object
EmployeeID        int64
OrderDate        object
RequiredDate     object
ShippedDate      object
Freight         float64
dtype: object

In [4]:
#меняем тип данных дат на datetime64

df_o['OrderDate'] = pd.to_datetime(df_o['OrderDate'])
df_o['RequiredDate'] = pd.to_datetime(df_o['RequiredDate'])
df_o['ShippedDate'] = pd.to_datetime(df_o['ShippedDate'])

#выводим данные с df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,32.38
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,11.61
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,65.83
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,41.34
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02,NaT,24.95
826,11074,SIMOB,7,1998-05-06,1998-06-03,NaT,18.44
827,11075,RICSU,8,1998-05-06,1998-06-03,NaT,6.19
828,11076,BONAP,4,1998-05-06,1998-06-03,NaT,38.28
829,11077,RATTC,1,1998-05-06,1998-06-03,NaT,8.53

In [5]:
#преобразовать строку в дату можно еще на стадии считывания данных с помощью параметра parse_dates:

df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';', parse_dates=['OrderDate', 'RequiredDate', 'ShippedDate'])

In [6]:
#извлекаем год из даты
df_o['year']=df_o['OrderDate'].dt.year

#появился столбец год
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,year
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,32.38,1996
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,11.61,1996
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,65.83,1996
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,41.34,1996
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,51.30,1996
...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02,NaT,24.95,1998
826,11074,SIMOB,7,1998-05-06,1998-06-03,NaT,18.44,1998
827,11075,RICSU,8,1998-05-06,1998-06-03,NaT,6.19,1998
828,11076,BONAP,4,1998-05-06,1998-06-03,NaT,38.28,1998
829,11077,RATTC,1,1998-05-06,1998-06-03,NaT,8.53,1998

In [7]:
#извлекаем месяцы недели и дни месяца
df_o['month']=df_o['OrderDate'].dt.month
df_o['day']=df_o['OrderDate'].dt.day
df_o['week']=df_o['OrderDate'].dt.isocalendar().week
#извлечение недели несколько отличается

#появились новые столбцы
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,year,month,day,week
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,32.38,1996,7,4,27
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,11.61,1996,7,5,27
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,65.83,1996,7,8,28
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,41.34,1996,7,8,28
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,51.30,1996,7,9,28
...,...,...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02,NaT,24.95,1998,5,5,19
826,11074,SIMOB,7,1998-05-06,1998-06-03,NaT,18.44,1998,5,6,19
827,11075,RICSU,8,1998-05-06,1998-06-03,NaT,6.19,1998,5,6,19
828,11076,BONAP,4,1998-05-06,1998-06-03,NaT,38.28,1998,5,6,19
829,11077,RATTC,1,1998-05-06,1998-06-03,NaT,8.53,1998,5,6,19

In [8]:
#считаем количетсво заказов по месяцам и годам
df_o.groupby(['year','month']).OrderID.count().reset_index()

    year  month  OrderID
0   1996      7       22
1   1996      8       25
2   1996      9       23
3   1996     10       26
4   1996     11       25
5   1996     12       31
6   1997      1       33
7   1997      2       29
8   1997      3       30
9   1997      4       31
10  1997      5       32
11  1997      6       30
12  1997      7       33
13  1997      8       33
14  1997      9       37
15  1997     10       38
16  1997     11       34
17  1997     12       48
18  1998      1       55
19  1998      2       54
20  1998      3       73
21  1998      4       74
22  1998      5       14

In [9]:
#Кроме года, месяца, номера недели и дня месяца из даты заказа можно также извлечь кварталы.
df_o['quarter'] = df_o['OrderDate'].dt.quarter

# Сводные таблицы

In [41]:
#Обнуляем изменения, сразу переводим дату в нужный формат
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';', parse_dates=['OrderDate', 'RequiredDate', 'ShippedDate'])

In [42]:
#вычленяем год, месяц, день месяца, квартал и неделю с даты заказа
df_o['Year'] = df_o['OrderDate'].dt.year
df_o['Month'] = df_o['OrderDate'].dt.month
df_o['Day'] = df_o['OrderDate'].dt.day
df_o['quarter'] = df_o['OrderDate'].dt.quarter
df_o['Week_ISO'] = df_o['OrderDate'].dt.isocalendar().week

#выводим 5 строк с датафрейма df_o
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Year,Month,Day,quarter,Week_ISO
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,32.38,1996,7,4,3,27
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,11.61,1996,7,5,3,27
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,65.83,1996,7,8,3,28
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,41.34,1996,7,8,3,28
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,51.30,1996,7,9,3,28

In [43]:
#сначала сгруппируем кол-во заказов по месяцу и году и сохраним отдельно этот датафрейм для дальнейшей работы
df_for_pivoting = df_o.groupby(['Year','Month']).OrderID.count().reset_index()

#проверяем что получилось
df_for_pivoting

    Year  Month  OrderID
0   1996      7       22
1   1996      8       25
2   1996      9       23
3   1996     10       26
4   1996     11       25
5   1996     12       31
6   1997      1       33
7   1997      2       29
8   1997      3       30
9   1997      4       31
10  1997      5       32
11  1997      6       30
12  1997      7       33
13  1997      8       33
14  1997      9       37
15  1997     10       38
16  1997     11       34
17  1997     12       48
18  1998      1       55
19  1998      2       54
20  1998      3       73
21  1998      4       74
22  1998      5       14

In [44]:
#теперь строим сводную таблицу
df_for_pivoting.pivot_table(index = 'Year', columns = 'Month', values = 'OrderID').reset_index()
#index - столбец, который расположится по вертикали
#columns - столбец, который расположится по горизонтали как название столбцов
#values - значения сводной таблицы

Month,Year,1,2,3,4,5,6,7,8,9,10,11,12
0,1996,NaN,NaN,NaN,NaN,NaN,NaN,22.0,25.0,23.0,26.0,25.0,31.0
1,1997,33.0,29.0,30.0,31.0,32.0,30.0,33.0,33.0,37.0,38.0,34.0,48.0
2,1998,55.0,54.0,73.0,74.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#заменим пустые значения на 0 с помощью аргумента fill_value
df_for_pivoting.pivot_table(index = 'Year', columns = 'Month', values = 'OrderID', fill_value= 0).reset_index()

Month,Year,1,2,3,4,5,6,7,8,9,10,11,12
0,1996,0.0,0.0,0.0,0.0,0.0,0.0,22.0,25.0,23.0,26.0,25.0,31.0
1,1997,33.0,29.0,30.0,31.0,32.0,30.0,33.0,33.0,37.0,38.0,34.0,48.0
2,1998,55.0,54.0,73.0,74.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
#на самом деле, можно было не делать промежуточный датафрейм для сводной таблицы
#вернёмся к df_o, выводим 5 строк с датафрейма df_o
df_o.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Year,Month,Day,quarter,Week_ISO
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,32.38,1996,7,4,3,27
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,11.61,1996,7,5,3,27
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,65.83,1996,7,8,3,28
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,41.34,1996,7,8,3,28
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,51.30,1996,7,9,3,28

In [16]:
#можно было сделать группировку и агрегацию непосредственно в методе .pivot_table().
#для этого добавляем аргумент aggfunc, в который передаем название агрегирующей функции
df_o.pivot_table(index = 'Year', columns = 'Month', values = 'OrderID', fill_value= 0, aggfunc='count').reset_index()

Month  Year   1   2   3   4   5   6   7   8   9  10  11  12
0      1996   0   0   0   0   0   0  22  25  23  26  25  31
1      1997  33  29  30  31  32  30  33  33  37  38  34  48
2      1998  55  54  73  74  14   0   0   0   0   0   0   0

#Дополнительные способы создания датафреймоф

In [17]:
#выводим данные с df_e
df_e

,EmployeeID,FirstName,LastName,Title,TitleOfCourtesy,BirthDate,HireDate,Address,HomePhone
0,1,Nancy,Davolio,Sales Representative,Ms.,1948-12-08 00:00:00.000,1992-05-01 00:00:00.000,507 - 20th Ave. E. Apt. 2A,(206) 555-9857
1,2,Andrew,Fuller,"Vice President, Sales",Dr.,1952-02-19 00:00:00.000,1992-08-14 00:00:00.000,908 W. Capital Way,(206) 555-9482
2,3,Janet,Leverling,Sales Representative,Ms.,1963-08-30 00:00:00.000,1992-04-01 00:00:00.000,722 Moss Bay Blvd.,(206) 555-3412
3,4,Margaret,Peacock,Sales Representative,Mrs.,1937-09-19 00:00:00.000,1993-05-03 00:00:00.000,4110 Old Redmond Rd.,(206) 555-8122
4,5,Steven,Buchanan,Sales Manager,Mr.,1955-03-04 00:00:00.000,1993-10-17 00:00:00.000,14 Garrett Hill,(71) 555-4848
5,6,Michael,Suyama,Sales Representative,Mr.,1963-07-02 00:00:00.000,1993-10-17 00:00:00.000,Coventry House Miner Rd.,(71) 555-7773
6,7,Robert,King,Sales Representative,Mr.,1960-05-29 00:00:00.000,1994-01-02 00:00:00.000,Edgeham Hollow Winchester Way,(71) 555-5598
7,8,Laura,Callahan,Inside Sales Coordinator,Ms.,1958-01-09 00:00:00.000,1994-03-05 00:00:00.000,4726 - 11th Ave. N.E.,(206) 555-1189
8,9,Anne,Dodsworth,Sales Representative,Ms.,1966-01-27 00:00:00.000,1994-11-15 00:00:00.000,7 Houndstooth Rd.,(71) 555-4444

In [18]:
#выводим должности сотрудников
df_e['Title']

0        Sales Representative
1       Vice President, Sales
2        Sales Representative
3        Sales Representative
4               Sales Manager
5        Sales Representative
6        Sales Representative
7    Inside Sales Coordinator
8        Sales Representative
Name: Title, dtype: object

In [19]:
#пример создания датафрейма, состоящего из двух столбцов, из двух серий
pd.DataFrame({'Title': df_e['Title'], 'Title2': df_e['Title']})

                      Title                    Title2
0      Sales Representative      Sales Representative
1     Vice President, Sales     Vice President, Sales
2      Sales Representative      Sales Representative
3      Sales Representative      Sales Representative
4             Sales Manager             Sales Manager
5      Sales Representative      Sales Representative
6      Sales Representative      Sales Representative
7  Inside Sales Coordinator  Inside Sales Coordinator
8      Sales Representative      Sales Representative

In [46]:
df_e.head()

,TitleOfCourtesy,Sex,EmployeeID,FirstName,LastName,Title,BirthDate,HireDate,Address,HomePhone
0,Ms.,female,1,Nancy,Davolio,Sales Representative,1948-12-08 00:00:00.000,1992-05-01 00:00:00.000,507 - 20th Ave. E. Apt. 2A,(206) 555-9857
1,Ms.,female,3,Janet,Leverling,Sales Representative,1963-08-30 00:00:00.000,1992-04-01 00:00:00.000,722 Moss Bay Blvd.,(206) 555-3412
2,Ms.,female,8,Laura,Callahan,Inside Sales Coordinator,1958-01-09 00:00:00.000,1994-03-05 00:00:00.000,4726 - 11th Ave. N.E.,(206) 555-1189
3,Ms.,female,9,Anne,Dodsworth,Sales Representative,1966-01-27 00:00:00.000,1994-11-15 00:00:00.000,7 Houndstooth Rd.,(71) 555-4444
4,Dr.,male,2,Andrew,Fuller,"Vice President, Sales",1952-02-19 00:00:00.000,1992-08-14 00:00:00.000,908 W. Capital Way,(206) 555-9482

In [20]:
#другой пример
#выберем уникальные обращения
df_e['TitleOfCourtesy'].unique()

array(['Ms.', 'Dr.', 'Mrs.', 'Mr.'], dtype=object)

In [21]:
#создание датафрейма с обращениями и полом с помощью словаря
df_sex = pd.DataFrame({'TitleOfCourtesy': ['Ms.', 'Dr.', 'Mrs.', 'Mr.'], 'Sex': ['female','male','female','male']})

df_sex

  TitleOfCourtesy     Sex
0             Ms.  female
1             Dr.    male
2            Mrs.  female
3             Mr.    male

In [22]:
#добавляем столбец sex в датафрейм df_e
df_e = df_sex.merge(df_e)

In [23]:
#проверяем добавился ли столбец
df_e.head()

,TitleOfCourtesy,Sex,EmployeeID,FirstName,LastName,Title,BirthDate,HireDate,Address,HomePhone
0,Ms.,female,1,Nancy,Davolio,Sales Representative,1948-12-08 00:00:00.000,1992-05-01 00:00:00.000,507 - 20th Ave. E. Apt. 2A,(206) 555-9857
1,Ms.,female,3,Janet,Leverling,Sales Representative,1963-08-30 00:00:00.000,1992-04-01 00:00:00.000,722 Moss Bay Blvd.,(206) 555-3412
2,Ms.,female,8,Laura,Callahan,Inside Sales Coordinator,1958-01-09 00:00:00.000,1994-03-05 00:00:00.000,4726 - 11th Ave. N.E.,(206) 555-1189
3,Ms.,female,9,Anne,Dodsworth,Sales Representative,1966-01-27 00:00:00.000,1994-11-15 00:00:00.000,7 Houndstooth Rd.,(71) 555-4444
4,Dr.,male,2,Andrew,Fuller,"Vice President, Sales",1952-02-19 00:00:00.000,1992-08-14 00:00:00.000,908 W. Capital Way,(206) 555-9482

In [24]:
#у нас появился пол работника на основании обращения к нему

#Категоризация непрерывных переменных

Признаки делятся на дискретные и непрерывные. Дискретные признаки могут принимать только определенные значения. Они могут быть:

-числовыми, например: количество заказов или ID продукта;

-в виде текста, например: название категории или название должности.

Непрерывные признаки не ограничиваются определенными отдельными значениями, а могут принимать любое значение в непрерывном диапазоне. Между любыми двумя непрерывными значениями может быть бесконечное число других. Непрерывные признаки всегда числовые. Примеры непрерывных признаков: стоимость товара, выручка, вес заказа.

Чуть выше мы разобрали один способ категоризировать дискретные признаки. мы исходя из обращения создали признак пол. Для этого мы создали вспомогательный датафрейм с столбцами: пол и обращение.

Теперь рассмотрим способ категоризировать числовые признаки, в том числе и непрерывные.

In [25]:
#выводим 5 строк с df_p
df_p.head()

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...

In [48]:
#с помощью метода .cut() разбиваем стоймость на 4 равных бина (группы, отрезка). Добавляем новый столбец
df_p['bins']=pd.cut(df_p['UnitPrice'],4)

df_p

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description,bins
0,1,Chai,10 boxes x 20 bags,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales,"(2.239, 67.75]"
1,2,Chang,24 - 12 oz bottles,19.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales,"(2.239, 67.75]"
2,3,Aniseed Syrup,12 - 550 ml bottles,10.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,"(2.239, 67.75]"
3,4,Chef Anton's Cajun Seasoning,48 - 6 oz jars,22.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,"(2.239, 67.75]"
4,5,Chef Anton's Gumbo Mix,36 boxes,21.35,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,"(2.239, 67.75]"
...,...,...,...,...,...,...,...,...
72,73,Rod Kaviar,24 - 150 g jars,15.00,8,Seafood,Seaweed and fish,"(2.239, 67.75]"
73,74,Longlife Tofu,5 kg pkg.,10.00,7,Produce,Dried fruit and bean curd,"(2.239, 67.75]"
74,75,Rhonbrau Klosterbier,24 - 0.5 l bottles,7.75,1,Beverages,Soft drinks. coffees. teas. beers. and ales,"(2.239, 67.75]"
75,76,Lakkalikoori,500 ml,18.00,1,Beverages,Soft drinks. coffees. teas. beers. and ales,"(2.239, 67.75]"
76,77,Original Frankfurter gr?ne Sobe,12 boxes,13.00,2,Condiments,Sweet and savory sauces. relishes. spreads. an...,"(2.239, 67.75]"

In [27]:
#группируем по бинам
df_p.groupby('bins').ProductID.count()

/tmp/ipython-input-2200415611.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_p.groupby('bins').ProductID.count()

bins
(2.239, 67.75]     73
(67.75, 133.0]      3
(133.0, 198.25]     0
(198.25, 263.5]     1
Name: ProductID, dtype: int64

In [28]:
#видим, что из 77 товаров 73 приходятся на нижнюю группу цены

In [29]:
#мы также можем сами формировать границы бинов
df_p['bins']=pd.cut(df_p['UnitPrice'], bins= [0,10,20,30,40])

#группируем по бинам
df_p.groupby('bins').ProductID.count()

/tmp/ipython-input-122903411.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_p.groupby('bins').ProductID.count()

bins
(0, 10]     14
(10, 20]    26
(20, 30]    13
(30, 40]    12
Name: ProductID, dtype: int64

In [30]:
#стоит обратить внимание, что сюда попали не все товары

#в этом можно убедиться. Сортируем стоймость по убыванию и видим, что когда мы сами формируем диапазоны бинов, бины могут сформироваться не для всех цен
df_p.sort_values('UnitPrice',ascending = False)

,ProductID,ProductName,Product_Description,UnitPrice,CategoryID,CategoryName,Category_Description,bins
37,38,C?te de Blaye,12 - 75 cl bottles,263.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales,NaN
28,29,Th?ringer Rostbratwurst,50 bags x 30 sausgs.,123.79,6,Meat/Poultry,Prepared meats,NaN
8,9,Mishi Kobe Niku,18 - 500 g pkgs.,97.00,6,Meat/Poultry,Prepared meats,NaN
19,20,Sir Rodney's Marmalade,30 gift boxes,81.00,3,Confections,Desserts. candies. and sweet breads,NaN
17,18,Carnarvon Tigers,16 kg pkg.,62.50,8,Seafood,Seaweed and fish,NaN
...,...,...,...,...,...,...,...,...
53,54,Tourtiere,16 pies,7.45,6,Meat/Poultry,Prepared meats,"(0.0, 10.0]"
51,52,Filo Mix,16 - 2 kg boxes,7.00,5,Grains/Cereals,Breads. crackers. pasta. and cereal,"(0.0, 10.0]"
12,13,Konbu,2 kg box,6.00,8,Seafood,Seaweed and fish,"(0.0, 10.0]"
23,24,Guaran? Fant?stica,12 - 355 ml cans,4.50,1,Beverages,Soft drinks. coffees. teas. beers. and ales,"(0.0, 10.0]"
32,33,Geitost,500 g,2.50,4,Dairy Products,Cheeses,"(0.0, 10.0]"

In [31]:
#добавляем названия бинов
df_p['bins']=pd.cut(df_p['UnitPrice'], bins= [0,10,20,30,40],labels=['от 1 до 10','от 10 до 20','от 20 до 30','от 30 до 40'])

df_p.groupby('bins').ProductID.count()

/tmp/ipython-input-2677439938.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_p.groupby('bins').ProductID.count()

bins
от 1 до 10     14
от 10 до 20    26
от 20 до 30    13
от 30 до 40    12
Name: ProductID, dtype: int64

In [32]:
#с помощью метода .qcut() разбиваем стоймость на 4 бина. При этом кол-во товаров в бинах стримится к одинаковому
df_p['bins']=pd.qcut(df_p['UnitPrice'], 4)

#группируем по бинам
df_p.groupby('bins').ProductID.count()

/tmp/ipython-input-1768030292.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_p.groupby('bins').ProductID.count()

bins
(2.499, 13.25]    20
(13.25, 19.5]     19
(19.5, 33.25]     19
(33.25, 263.5]    19
Name: ProductID, dtype: int64

#Замена значений в датафреймах

In [33]:
#обнулим предыдущие манипуляции с датафреймом с заказами
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')

#выводим данные с df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [34]:
#смотрим есть ли пропуски
df_o.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       830 non-null    int64
 1   CustomerID    830 non-null    object
 2   EmployeeID    830 non-null    int64
 3   OrderDate     830 non-null    object
 4   RequiredDate  830 non-null    object
 5   ShippedDate   809 non-null    object
 6   Freight       830 non-null    float64
dtypes: float64(1), int64(2), object(4)
memory usage: 45.5+ KB

In [35]:
#видим, что количество значений ShippedDate меньше остальных. Но такой способ не самый информативный

In [36]:
#метод .isnull() возращает True, если есть пропуск
df_o.isnull()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
825,False,False,False,False,False,True,False
826,False,False,False,False,False,True,False
827,False,False,False,False,False,True,False
828,False,False,False,False,False,True,False
829,False,False,False,False,False,True,False

In [37]:
#считаем кол-во пропусков
df_o.isnull().sum()

OrderID          0
CustomerID       0
EmployeeID       0
OrderDate        0
RequiredDate     0
ShippedDate     21
Freight          0
dtype: int64

In [49]:
#заменяем все пропуски столбца на дату с помощью метода .fillna()
df_o['ShippedDate'] = df_o['ShippedDate'].fillna('2025-11-24 11:55:00.000')

#проверяем
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Year,Month,Day,quarter,Week_ISO
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16 00:00:00,32.38,1996,7,4,3,27
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10 00:00:00,11.61,1996,7,5,3,27
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12 00:00:00,65.83,1996,7,8,3,28
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15 00:00:00,41.34,1996,7,8,3,28
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11 00:00:00,51.30,1996,7,9,3,28
...,...,...,...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02,2025-11-24 11:55:00,24.95,1998,5,5,2,19
826,11074,SIMOB,7,1998-05-06,1998-06-03,2025-11-24 11:55:00,18.44,1998,5,6,2,19
827,11075,RICSU,8,1998-05-06,1998-06-03,2025-11-24 11:55:00,6.19,1998,5,6,2,19
828,11076,BONAP,4,1998-05-06,1998-06-03,2025-11-24 11:55:00,38.28,1998,5,6,2,19
829,11077,RATTC,1,1998-05-06,1998-06-03,2025-11-24 11:55:00,8.53,1998,5,6,2,19

In [39]:
#заменяем в столбце ShippedDate значение 1996-07-16 00:00:00.000 на notshipped с помошью метода .replace()
df_o['ShippedDate']= df_o['ShippedDate'].replace('1996-07-16 00:00:00.000','notshipped')
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,notshipped,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,2022-05-01 00:00:00.000,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,2022-05-01 00:00:00.000,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,2022-05-01 00:00:00.000,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,2022-05-01 00:00:00.000,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,2022-05-01 00:00:00.000,8.53

In [ ]:
# Метод where в pandas используется для выборочного сохранения или замены значений в DataFrame или Series на основе заданного условия.
# Он работает по принципу "сохранять, где условие истинно, заменять, где ложно"

In [50]:
#заменяем значения столбца ShippedDate для заказов 11076,11077 на Notshipped
df_o['ShippedDate'] =df_o['ShippedDate'].where(~(df_o['OrderID'].isin([11076,11077])), 'Notshipped')

#проверяем
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight,Year,Month,Day,quarter,Week_ISO
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16 00:00:00,32.38,1996,7,4,3,27
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10 00:00:00,11.61,1996,7,5,3,27
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12 00:00:00,65.83,1996,7,8,3,28
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15 00:00:00,41.34,1996,7,8,3,28
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11 00:00:00,51.30,1996,7,9,3,28
...,...,...,...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02,2025-11-24 11:55:00,24.95,1998,5,5,2,19
826,11074,SIMOB,7,1998-05-06,1998-06-03,2025-11-24 11:55:00,18.44,1998,5,6,2,19
827,11075,RICSU,8,1998-05-06,1998-06-03,2025-11-24 11:55:00,6.19,1998,5,6,2,19
828,11076,BONAP,4,1998-05-06,1998-06-03,Notshipped,38.28,1998,5,6,2,19
829,11077,RATTC,1,1998-05-06,1998-06-03,Notshipped,8.53,1998,5,6,2,19