# Срезы

In [2]:
#импортируем библиотеку pandas
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

#считываем данные с файлов
df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

Mounted at /content/drive

In [ ]:
#выводим данные с df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#выводим строки с индексами от 5 до 9
df_o[5:10]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
5,10253,HANAR,3,1996-07-10 00:00:00.000,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
6,10254,CHOPS,5,1996-07-11 00:00:00.000,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
7,10255,RICSU,9,1996-07-12 00:00:00.000,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
8,10256,WELLI,3,1996-07-15 00:00:00.000,1996-08-12 00:00:00.000,1996-07-17 00:00:00.000,13.97
9,10257,HILAA,4,1996-07-16 00:00:00.000,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,81.91

In [ ]:
#выводим строки с индексами от 0 до 9
df_o[:10]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
5,10253,HANAR,3,1996-07-10 00:00:00.000,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
6,10254,CHOPS,5,1996-07-11 00:00:00.000,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
7,10255,RICSU,9,1996-07-12 00:00:00.000,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
8,10256,WELLI,3,1996-07-15 00:00:00.000,1996-08-12 00:00:00.000,1996-07-17 00:00:00.000,13.97
9,10257,HILAA,4,1996-07-16 00:00:00.000,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,81.91

In [ ]:
#выводим строки с индексами от 5
df_o[5:]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
5,10253,HANAR,3,1996-07-10 00:00:00.000,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
6,10254,CHOPS,5,1996-07-11 00:00:00.000,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
7,10255,RICSU,9,1996-07-12 00:00:00.000,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
8,10256,WELLI,3,1996-07-15 00:00:00.000,1996-08-12 00:00:00.000,1996-07-17 00:00:00.000,13.97
9,10257,HILAA,4,1996-07-16 00:00:00.000,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,81.91
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#выводим строки с индексами от 5, за исключением 5 строк в конце
df_o[5:-5]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
5,10253,HANAR,3,1996-07-10 00:00:00.000,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
6,10254,CHOPS,5,1996-07-11 00:00:00.000,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
7,10255,RICSU,9,1996-07-12 00:00:00.000,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
8,10256,WELLI,3,1996-07-15 00:00:00.000,1996-08-12 00:00:00.000,1996-07-17 00:00:00.000,13.97
9,10257,HILAA,4,1996-07-16 00:00:00.000,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,81.91
...,...,...,...,...,...,...,...
820,11068,QUEEN,8,1998-05-04 00:00:00.000,1998-06-01 00:00:00.000,NaN,81.75
821,11069,TORTU,1,1998-05-04 00:00:00.000,1998-06-01 00:00:00.000,1998-05-06 00:00:00.000,15.67
822,11070,LEHMS,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,136.00
823,11071,LILAS,1,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,0.93
824,11072,ERNSH,4,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,258.64

In [ ]:
# Методы .iloc и .loc в Pandas отличаются подходом к индексации данных.
# Оба используются для выбора строк и столбцов, но .iloc работает на основе целочисленных позиций, а .loc — на основе меток.

In [ ]:
#выводим строки с индексами с 5 до 9 и столбцы с индексами от 1 до 2
df_o.iloc[5:10, 1:3]

  CustomerID  EmployeeID
5      HANAR           3
6      CHOPS           5
7      RICSU           9
8      WELLI           3
9      HILAA           4

In [ ]:
#выводим данные с df_o
df_o

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#делаем OrderID индексом для строк
df_o = df_o.set_index('OrderID')

In [ ]:
#смотрим что получилось
df_o

,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
OrderID,,,,,,
10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
...,...,...,...,...,...,...
11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,24.95
11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,18.44
11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,6.19
11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,38.28
11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,8.53

In [ ]:
#выбор строк по индексам все равно работает
df_o.iloc[0:10]

,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
OrderID,,,,,,
10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,32.38
10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,11.61
10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,65.83
10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,41.34
10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,51.30
10253,HANAR,3,1996-07-10 00:00:00.000,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,58.17
10254,CHOPS,5,1996-07-11 00:00:00.000,1996-08-08 00:00:00.000,1996-07-23 00:00:00.000,22.98
10255,RICSU,9,1996-07-12 00:00:00.000,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,148.33
10256,WELLI,3,1996-07-15 00:00:00.000,1996-08-12 00:00:00.000,1996-07-17 00:00:00.000,13.97
10257,HILAA,4,1996-07-16 00:00:00.000,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,81.91

In [ ]:
#выводим строки с индексами [10248,10249] и столбцы ['CustomerID','EmployeeID']
df_o.loc[[10248,10249],['CustomerID','EmployeeID']]

        CustomerID  EmployeeID
OrderID
10248        VINET           5
10249        TOMSP           6

# Метод apply()

In [ ]:
#считываем данные с файлов
df_p = pd.read_csv('/content/drive/MyDrive/Products.csv', sep = ';')
df_c = pd.read_csv('/content/drive/MyDrive/Customers.csv', sep = ';')
df_o = pd.read_csv('/content/drive/MyDrive/Orders.csv', sep = ';')
df_od = pd.read_csv('/content/drive/MyDrive/Order_details.csv', sep = ';')
df_e = pd.read_excel('/content/drive/MyDrive/Employees.xlsx')

In [ ]:
df_c.head()

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
1,ANATR,Ana Trujillo,Owner,(5) 555-4729,Avda. de la Constitucion 2222
2,ANTON,Antonio Moreno,Owner,(5) 555-3932,Mataderos 2312
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
4,BERGS,Christina Berglund,Order Administrator,0921-12 34 65,Berguvsv?gen 8

Метод apply() в библиотеке Pandas позволяет применять пользовательскую функцию к каждому элементу или группе элементов в DataFrame или Series.

In [ ]:
df_c['Phone'].apply(lambda x: x.replace('-','').replace(' ','')) #удаляем из данных в столбце знаки пробела и '-'

0       0300074321
1       (5)5554729
2       (5)5553932
3     (171)5557788
4       0921123465
          ...
86       981443655
87     (14)5558122
88    (206)5554112
89       902248858
90     (26)6427012
Name: Phone, Length: 91, dtype: object

In [ ]:
df_c['Phone'].str.replace('-','') #можно удалить знаки используя строчные методы

0        0300074321
1       (5) 5554729
2       (5) 5553932
3     (171) 5557788
4      092112 34 65
          ...
86        981443655
87     (14) 5558122
88    (206) 5554112
89       90224 8858
90     (26) 6427012
Name: Phone, Length: 91, dtype: object

В качестве функции в методе apply() можно использовать не только лямбда-функции, но и любые другие.